### ISSUE TITLE
Troll combo: CD reduction talents+ Skills and phase

### ISSUE THREAD

**Issue by shog0** [darklordabc/Legends-of-Dota-Redux#1012]
I.e. Sniper with phase, Elemental mystery(CD reduction), Blink, glaves and so on. Could attack from phase or in between phases, we could not get to him. He moved around without risks by bkinking in the "phase" state. He could even stand in the fountain phasing and killing the whole team without risk. 

Totally a troll combo.

**Comment by LoDfan** [comment]
100% Agree. If you're playing with a friend and arcane symbiosis isn't banned = 100% win.
The problem is WR and Sniper don't need cd reduction abilities to use phase non stop. Only octarine and talent. That is a problem.
My favorite troll build is based on tiny + pulse nova. Tiny has good talents for that, but you need high level and octarine core

**Comment by darklordabc** [comment]
I think Symbiote using its hosts health as backup mana is a bit IMBA. For example if you have death pulse, you can basically cast it forever, because the heal mostly makes up for the health cost the host pays. It also makes the bonus mana regen kind of redundant. 

Its very easy for a tank to get lots of health points that the symbiote can use for mana.

**Comment by LoDfan** [comment]
But more powerful is full dps Symbiote with aganim (morph to agi from 2 stats, 3 damage passives and AS ability as an example).

**Comment by darklordabc** [comment]
@OtsoTurpeinen did you get around to making the symbiote disabled when the host is disabled, I dont think thats currently the case.

**Comment by darklordabc** [comment]
Most cooldown manipulating abilities are troll combos with each others now and phase shift ability has been banished to single player abilities so I think this issue is mostly dealt with, however, its likely there is still remaining issues with cooldown reduction strategies in general and we will probably have to find a solution in the future.
