### ISSUE TITLE
New Ability Ideas

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1019]
Just a thread to dump some ability ideas 
![image](https://cloud.githubusercontent.com/assets/16277198/26220663/d65ea284-3c56-11e7-9ff4-8186247ec58a.png)
![image](https://cloud.githubusercontent.com/assets/16277198/26220805/790bf1b2-3c57-11e7-80dc-e7adb150424a.png)

**Comment by lewisallen** [comment]
What about Feast inverse? Damage/Lifesteal based on targets missing hp instead of current HP. Percentages might have to be reduced though.

**Comment by darklordabc** [comment]
Is'nt that like vipers ability? That does more damage on missing HP.

**Comment by lewisallen** [comment]
Yes, but Viper's ability is fixed numbers based on every 20% missing. This scales better late game. It's just an idea though.

**Comment by iprobie** [comment]
**Smite**
Damage Type: Pure
Pierces Spell Immunity: No
Can be dispelled: Yes
Smites a target, dealing  damage based on its maximum health. A hero who has been Smitten is immune to further Smites for 4 seconds.
_The buff on the target which renders it immune to Smite is purgeable_
Damage: 12/16/20/24% of enemy's max HP
Cast range: 675
Mana Cost: 120/140/160/180
Cooldown: 13

**Energy Drain**
Pierces Spell Immunity: No
Steals mana from the target.
_Mana stolen and mana gained is independent of each other, meaning you  still gain mana even if the enemy does not have any._
Mana Stolen: 120/180/240/300
Cast range: 950
Mana Cost: 0
Cooldown: 30

**Comment by CaptainDildac** [comment]
[No_Target] [Affects Self]
Feint - Gain a massive bonus to his magic resist and evasion for a short duration. Each attack you evade while Feint is active restores your mana by a percentage of its max value. Can be cast while disabled and disjoints projectiles on cast.
Magic Resist Bonus: 95%
Evasion Bonus: 100%
Buff Duration: 1.5/1.7/1.9/2.1
Max Mana Restore: 1.5%
Mana Cost: 100/90/80/70
Cooldown: 19/17.5/16/14.5

[Unit_Target] [Affects Enemies and Allies]
Informant’s Hex - Mark a target non-hero unit granting vision in a large area around them and causing them to grant you bonus gold if they die. If the killer of the hexed target is your enemy they will take magic damage. For each informant under your influence, you gain increased movement speed.
Duration: 60/80/100/120
Vision Radius: 1000
Bonus Gold on Death: 10/25/40/55
Magic Damage on Death: 100/175/250/325
Movement Speed Bonus per Informant: 4%
Cast Range: 400/600/800/1000
Mana Cost: 50/70/90/110
Cooldown: 10

**Comment by CaptainDildac** [comment]
This was inspired by looking at the most under utilized flesh heaps, evasion heap being one of the lesser picked of them all seeing as how it comes online around the same time that opponents get their MKB's.

The Problem of Evasion: Generally seen as a stat that is too easily countered to invest much interest into. Beyond using large quantities of evasion to rat, MKB essentially invalidates evasion in the PvP environment further cementing it as a PvE move.

Proposed Answer: Give players a reason to have evasion beyond its initial use with additional abilities. Anything from a passive scaling of another stat depending on your evasion or a move that has an effect that is more powerful based on upon your evasion. This makes it so when the eventual MKB's hit you will still be gaining some sort of tactical advantage from any evasion you have accumulated through items and abilities. Now evasion has always had the flavor of physical finesse outwitting an opponents strikes so why not use Evasion as a stat that some "brawler" or "martial arts" flavored abilities could scale with.

Examples [WARNING: tool-tip values subject to change]

[Passive] [Affects Self] 
Wind Style - You gain increased movement speed depending on the amount of evasion you have, additionally whenever you evade an attack you temporarily gain bonus agility. This bonus stacks on itself up to a max of three stacks.
Movement Speed per Evasion: .20/.40/.60/.80 [<-- MKB cant stop your potential 80 movement speed bonus]
Bonus Agility upon Evade: 5/7/9/11 [<-- Pulling creep aggro and diving non-sniper towers turns your evasion of lesser enemy attacks against your foes, even if they have MKB their creeps dont!]
Max Stacks: 3
Stack Duration: 7 seconds 

[Unit_Target] [Affects Enemies]
Elusive Strike - Deliver a swift disorienting attack on your opponent mini-stunning them and disabling their passives temporarily based on the amount of evasion you have.
Magic Damage: 100/170/240/310
Mini-Stun Duration: 0.25
Base Break Duration: 2 seconds [Break could be replaced and re-balanced with another CC type]
Bonus Break Duration per Evasion: .05 [<-- Again a bonus that persists after your evasion is negated, max of 5 extra seconds of Break at 100% evasion]
Cast Range: 200
Mana Cost: 100/110/120/130
Cooldown: 17/16/15/14

Thoughts? Is this too adventurous? Is MKB and evasion fine the way it is or could their be room for Evasion to have some viability outside of PvE late game? Is this even possible with the commands valve gives us in Lua?

**Comment by DankBudd** [comment]
> Is this even possible with the commands valve gives us in Lua?

yes

> Is this too adventurous? Is MKB and evasion fine the way it is or could their be room for Evasion to have some viability outside of PvE late game?

mkb is an item slot that gets eaten up to deal with your evasion, but i agree that evasion should do more.

**Comment by Exchy** [comment]
Rubick type ultimate, but not for ultimate : it might be Q spell steal or W spell steal or my dream - passive steal. Make them separate abilities, so I could take Q steal.

**Comment by Darkmega18** [comment]
Well since this is here, I'm gonna throw a few in.

Combo Master: Each successive strike on any unit up to a maximum number of hits builds bonus damage. Upon hitting max stacks all stacks are consumed and the user causes a critical hit combined with a greater bash effect. The effect times out if not attacking for a few seconds. A target who just got bashed cannot be rebashed by this ability for 2 seconds afterwards (counting after the stun expires) but will still take critical damage.
Strikes Max: 5
Bonus damage per hit: 8/16/24/32
Last strike crit: 300%
Last strike Bash duration: 0.6/0.8/1/1,2

Flurry
Skillshot melee version of hawkeye's rapidfire with mobility. Dashes the player a short distance towards the target point. If he hits an enemy unit it stuns them briefly before unleashing a number of rapid consecutive attacks which have their damage reduced but apply onhit effects. Aghanims causes the flurry to hit all nearby enemies simultaneously and stun the main unit for twice as long.
Attacks: 3/4/5/6
Damage output: 50%/55%/60%/65%
Stun duration: 0.5
Attack timing: one per 0.25 secs
Dash max distance: 400/500/600/700
Aghs radius: 300/350/400/450
Aghs Stun: 1

**Comment by DankBudd** [comment]
@Darkmega18 the first one is just "lets throw all the op shit together".. fury swipes + bash + crit doesnt seem very creative.

but i support the second ability 👍
would be nice if it hit in like a cone shaped aoe in front of the hero, and with scepter have it be all around you.

**Comment by Darkmega18** [comment]
yeah, but the damage doesn't go to buggery like fury swipes and it's based on just the player not the one you're comboing. you can hit some other thing 4 times then switch target to bash another guy for the critical then example target your flurry to the other person and unleash the whole combo and end up bashing them too. Since it's basically how in action games with weapons they usually have attack combos and stuff... I do admit my damage is probably a little high on it considering it's gonna go crit, but it's only after the 5 attacks go up and it resets back to 0 bonus. :V the crit at lower levels could probably also come down too, but theres already a built in counter measure to being permabashed from insane rapidfire comboing on it already.

Another thing I thought was a combo version that is for casters:

Psionic Flow: The hero feels the flow of mana as he strikes out lashing out in a deadly dance of magic and strength. Every 3 auto attacks gives you a charge to critically strike with magic damage, and every 3 spells cast give you a critical strike. auto Crit stacks build up separately but time out after 5 seconds of not attacking or 10 seconds when not spell casting. Aghanims causes triggered criticals to restore mana or health based on damage dealt through lifesteal.
Attacks or spells to trigger: 3
Critical Power: 150%/175%/200%/225%
Aghs Physical Critical Lifesteal: 50%/60%/70%/80%
Magical Critical Damage to Mana restore: 25%/40%/55%/70% (restoration is the amount of damage dealt then converted into mana)
