### ISSUE TITLE
Using New Abilities Bonus (Originality Bonus)

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1066]
Add a new mechanic to the skill picking phase which rewards players for using abilities they have never used, or rarely used. If anyone has suggestions or ideas related to this mechanic, I'm keen to hear them. 
Notes:
![image](https://user-images.githubusercontent.com/16277198/27066984-6e6995d6-504b-11e7-91fa-f3a309fa3011.png)
The option should be customizble, so players can decide how much gold bonus they get from new abiliites, and also what threshold to decide what is a new ability. Default is 20%, meaning the 20% of the player LEAST used the ability, will count as new abilities and grant the bonus. 
![image](https://user-images.githubusercontent.com/16277198/27067706-ac242964-504f-11e7-9573-7cd024f82bca.png)

*Abilities in the least 20% of the players used abilities, should count as originality bonus. All abilities are counted in a players list, most will have 0 usage, but they should still be counted in the list, so that 20% lowest usage ability will almost always be unused abilities, but if a player has used all the abilities, it will be possible for him/her to get the bonus even tho they have used the ability before.
*The bonus will be in form of an item that the players will start the game with, stackable, when they use the item they will gain some gold, similar to a tome of knowledge
*Gold gained from the bonus should be adjustable
*Gains bonus per ability, the maximum = maximum amount of ability slots enabled, in most cases 6.
*Does not apply to bots

**Comment by 1ran-wang** [comment]
This system should be player independent. Because for most Lod player. They just copying the strongest build they saw. A good way to encourage people play different build is, make the fun builds(Or new build) are able to fight (or at least, kill)them.

Normally right click build is easily to defeat fun build player, So creative build means lose and can't reach levels they need.

I recommend 3 different ways.

For 3000 starting gold:
Start gold bonus:
1. Pick abilities you never used gain 400 gold and 1 level/each at start.  
2. Pick abilities rarely used gain 200 gold and 0.5 level/each at start.
3. Pick Hottest abilities (Top 20)  will make you lose 250 gold/each at start.

Or gold per tick bonus.
Gold per tick:
1. Pick abilities you never used gain bonus 2 gold 2 exp/tick . 
2. Pick abilities rarely used gain 1 gold 1 exp/tick at start.

I highly recommend bonus gold and exp. because Items and levels are important to discover new powerful combo.

Another way:
1. for each skill you picked that in Hottest list, all your damage will deduce by 5%。
2. for each skill you picked that in Rarely list, all your damage will Increase by 5%
3. if you use rarely abilities to build totally non-passive build. All your cool down will deduce by 20%
(Windrunner's perk)
4.if you use rarely abilities to build totally passive build. your gold rate/exp rate will increase by 10%

**Comment by darklordabc** [comment]
Thanks for your suggestion @testiclesbomber, I was going to orginally do exp and gold, but I thought it would make it needlessly complicated and harder to balance, so I decided with just the gold bonus.
