### ISSUE TITLE
[Suggestion] Teleporting Bots cheat me off gold and experience

### ISSUE THREAD

**Issue by Exchy** [darklordabc/Legends-of-Dota-Redux#1071]
When low enemy under the tower goes into ethereal form and then tp's to home, they receive xp for that. But the thing is, I was the one who brought them to that low hp when defing the tower. So my tower just tped 3 low hp enemies to home and I couldn't finish them off. Seemsgood. Maybe hero that made a damage will receive some exp as well?

**Comment by AugurM** [comment]
Those are free kills if you picked some form of magic damage.
It's the same as not being able to finish an enemy off and having him run away from you.
Their XP bonus is for the time it takes them to come back to the lane. Since you never left, why would you get a bonus?

**Comment by darklordabc** [comment]
I'd prefer to redo this a bit, the whole taunt and teleport thing is kind of hacky. But Augur is right, the exp bonus is because they are forced to return to base, but youre right that it can feel like your being cheated a bit, one solution is to get a magic damage ability that can finish them off but I know thats not an ideal solution. I have an idea on how to redo this mechanic but I might need another devs help.
