### ISSUE TITLE
Updating "Random Flesh Heap"

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#1150]
1. Could the new ones (Armor, Regens, MR, Lifesteal) be added to the pool and Attack Range be removed from the pool?

2. Offer options to have more than one randomly added at start (Yes, I love those very much). Maybe create special synergistic combinations of those just for the option.

3. Alter them to just be modifiers in tooltip form (like perks) in order to not clutter the UI with an ability already maxed.

4. Improve the tooltip with the current total added and maybe derived numbers too (eg. Agility added X, Attack Speed Y, Armor Z)

**Comment by darklordabc** [comment]
Why would we remove the attack range one?

**Comment by darklordabc** [comment]
I've done (1).

**Comment by AugurM** [comment]
Because Attack Range should be picked voluntarily, it has the potential to break builds. Not in the "greatly improve" sense (which it does most of the time), but in the "those abilities of mine are now irrelevant because I don't need to go to melee any more and my auras are useless now".
It is also aesthetic and prompted issue #1151 
Either that, or restrict the "randomness" to only be eligible to Attack Range as a Random Flesh Heap if your character is ranged to begin with?

**Comment by darklordabc** [comment]
Yeah I was about to change it so that melee heros dont get the attack range flesh heap, but then I realized that probably lots of melee builds would want that flesh heap, as its one of the best flesh heaps. I know there are some builds that will be hurt by range boosting flesh heap, but I dont think it happens enough to justify blocking it for melee heroes in general, especially since its one of the best flesh heaps, seems like a slight nerf to melee heros when free flesh heaps is on (for example, I'm sure a melee hero would hate getting vision where they would of got attack range).

**Comment by AnimaThunder** [comment]
Something that might help thia significantly is instead dropping a cap on how much range can be gained via that flesh heap. Obviously it would need to be somewhere in the 800's range to make getting it worth it, but it would prevent max atkspd juggernauts with fury swipes/bash from permanently dominating a game where they pop off, for example
