### ISSUE TITLE
Problem with SotF cooldown and spell amp not getting stacks in base

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#1168]
what if its later in the game and you're defending high ground? 
your build suddenly becomes weaker and you're at a disadvantage 

maybe you should add a check for nearby enemy heroes as well, and let them get stacks if any are found.
i know its might seem kind of arbitrary but it would work right?

**Comment by 1ran-wang** [comment]
Yes and also you can hide yourself in trees for stacks.
 So I'm thinking about make it only stacks when you are in enemy's vision. and stacks much faster than now.

**Comment by DankBudd** [comment]
definitely a better solution than what it currently is.

could put a grace period on it, so if you are not in enemy vision for X seconds then it stops gaining stacks.

**Comment by darklordabc** [comment]
I've changed it so that if there is an enemy hero within 3000 range, the anti-camping nerf will be disabled, meaning, you can still gain stacks in your base if there is an enemy hero nearby. 
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/2fc6a4de9e59b18dfab1a2dce84382615a04f8d4

**Comment by DankBudd** [comment]
the "being in enemy vision" solution is better than what i originally said, that should be used instead.

> you can hide yourself in trees for stacks.

this lion was hiding in the trees for the majority of the game
![20170810131325_1](https://user-images.githubusercontent.com/18477016/29182733-fb2b8e2a-7dcd-11e7-9572-998de722b255.jpg)

**Comment by darklordabc** [comment]
Doesnt look like it worked out for him. If a player hides in the trees the whole game, they wont get gold and their team will be missing a player, it doesnt sound like a winning strategy, and hence I dont see why we would nerf it.

**Comment by 1ran-wang** [comment]
I tried this build for 2-3 games. It's OP if any enemy left the game.Because Lion's perk make Zeus ult has only 30  sec cooldwon by farming offliner.

And also if your team defend for 20 mins, You can easily kill any enemy that lower than 2k hp.
the build will be 

[Lion: Blood rage + Arcane echo + Zeus ult + SOTF spell amp + Spell critical + Book of knowledge.]

go to the lane until you reach lv4 SOTF, then hide yourself in tree ks for early kills, build refresher so you can cast 4 ult. if you kill 2+ heroes you will get your 5th ult. 

because if you kill anybody in one single Zeus ult. it will reduce the cool down into 30 sec,  if you kill 2 in one single ult, you will refresh it instantly.

**Comment by DankBudd** [comment]
> Doesnt look like it worked out for him.

well the point is that shitty results arent gunna stop players from going afk in the trees. they will keep trying because it works sometimes because of the below quote


> It's OP if any enemy left the game.Because Lion's perk make Zeus ult has only 30 sec cooldwon by farming offliner.

yeah the io's in fountain are not invulnerable, so they can be farmed
