### ISSUE TITLE
[Suggestion] improve backdoor protection

### ISSUE THREAD

**Issue by igor-netFantom** [darklordabc/Legends-of-Dota-Redux#1170]
Please improve backdoor protection. Then creeps away and backdor protection is active make so enemy cant destroy towers so easy. Maybe much faster HP regen should helps or just make towers under backdoor protection untargetable. Anti-rat option didnt helps. Rat builds just teleport to tower and destroy it. Sitting under tower and waiting for them is not funny.

**Comment by 1ran-wang** [comment]
Yes, this is a huge problem I think.

**Comment by DankBudd** [comment]
i dont think this is a problem.
if people build for the sole purpose of ratting then they should be able to rat _(so long as their build isnt garbage)_

tp scrolls are a thing for a reason, and tp boots have lower cd if you can afford them.

however, if this does get added.. please dont just change a core mechanic of dota, make it a mutator and/or a vote.

**Comment by 1ran-wang** [comment]
well some rat build are not defendable.

2017年8月9日 下午7:31，"DankBudd" <notifications@github.com>写道：

i dont think this is a problem.
if people build for the sole purpose of ratting then they should be able to
rat *(so long as their build isnt garbage)*

tp scrolls are a thing for a reason, and tp boots have lower cd if you can
afford them.

however, if this does get added.. please dont just change a core mechanic
of dota, make it a mutator and/or a vote.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/darklordabc/Legends-of-Dota-Redux/issues/1170#issuecomment-321409220>,
or mute the thread

**Comment by darklordabc** [comment]
@igor-netFantom do you have examples of builds that do this?

I'm thinking maybe we could make towers take less damage (only 50?) when they have backdoor protection, and have it so that this change only works with anti-rat mutator activated? Anti-rat mutator is on in most games.

**Comment by igor-netFantom** [comment]
Tp scrolls and tp boots dont help. Rat-builds like Focus fire/Chemical rage + Grow + Demolish + Teleportation/Unstable rift + [some attack range extender] destroy tower for 5-10 seconds. You can't teleport in time in 5 seconds. Only 1 way to counter this - sit at base all time and wait for him - this is so boring.

**Comment by igor-netFantom** [comment]
> if people build for the sole purpose of ratting then they should be able to rat

I dont ask to make this bulids troll combo.  If they good at crashing bruildings, then OK, but only when creeps near and backdor protection  offline.

**Comment by igor-netFantom** [comment]
>I'm thinking maybe we could make towers take less damage (only 50?) when they have backdoor protection

Should be tested with this builds.  Rat-builds include max attack speed + dmg to buildings. They dont have big damage, but do it faster then tower regen HP.

>  and have it so that this change only works with anti-rat mutator activated

Its on at 50% games, but i think its only because it don't helps much against rats. I agree that it will be better to change backdoor protection only then Anti-rat mutator is on.

**Comment by darklordabc** [comment]
I made it so that when the anti-rat mutator is activated, towers with active backdoor protection do not receive damage. Is that okay?
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/2d9e001e5401fd7d42260e8be98a0026cf4bd88d

**Comment by igor-netFantom** [comment]
I check it - all OK. It works perfect.

**Comment by LoDfan** [comment]
Oh I really like improving backdoor protection. Because before I had to permaban spectral form because of it effectiveness in rat strategy. 
And before there were a lot of rat build hard to counter (SS Wards ult with arcan echo and TD = 4 casts of SS Wards, WR + Sven's ults, Pugna's blast with multicast and arcan crit etc..)
With this improve there is still possibility to destroy fast tier 2 towers, but it becomes more harder to destroy tier 3 towers. Thanks.

**Comment by 1ran-wang** [comment]
Thanks, I tried it. works well.

 the funny stuff is if you hit a tower in low hp with BD protection it will start to heal itself till it's full #new meta #Help enemies.
