### ISSUE TITLE
[OP] Spectral Form

### ISSUE THREAD

**Issue by 01der** [darklordabc/Legends-of-Dota-Redux#1182]
Spectral Form is too strong at destroying buildings in my opinion.
Most towers cant hit you and being magic dmg, you do full dmg to buildings.
At the very least it should not be available when op is off.
A fix could be to reduce building dmg while in spectral form (70% reduction maybe).
Otherwise we could reduce the duration and up the cd maybe.

**Comment by 1ran-wang** [comment]
What if we increase the damage income of spectral form?

**Comment by 01der** [comment]
the issue right now is that most towers don't do any damage to heroes in spectral form:
10x0 = 0
It encourages a Natures Prophet-like play-style only that you can take down towers solo from 100% to 0 in a matter of 4 seconds.

**Comment by DankBudd** [comment]
@darklordabc what do you think about Spectral Form doing less damage to buildings? It's fairly easy to implement.

**Comment by darklordabc** [comment]
Sure maybe make it do 50% damage to structures?

**Comment by 01der** [comment]
50% sounds fair. BTW dark rift seems to sometimes disable backdoor on outer towers. And i saw you made furion-teleport and dispersion a troll combo, then dark rift and dispersion should be also.

**Comment by DankBudd** [comment]
if it disables backdoor protection then whatever unit it uses should have its BaseClass changed to `npc_dota_base_additive`

and i agree it should be a troll combo

**Comment by LoDfan** [comment]
I wrote about Spectral Form to be OP some months ago in Discord, but nobody agree with me. So I just won 10 plays in a row with SF + Rage + other skills to destroy towers. Then I continued to permaban it.
I checked this skill increasing dmg to buildings on enemy base 3 times (because of lots of armor). 100 dmg without SF buff and ~300 dmg with SF buff. So 50% reduction is not enough I think. 66-80% will be fair enough. So this skill will be used only for hero killing, not towers killing.
