### ISSUE TITLE
[suggestion] Marksman

### ISSUE THREAD

**Issue by 01der** [darklordabc/Legends-of-Dota-Redux#1183]
in my opinion the scepter upgrade of Marksman is what makes it OP so a redux version without that could be added (str/int marksman don't have the upgrade either).

Maybe we could get the scepter upgrade as a separate skill (like sidegunner).
I suggest this:
attack gets split into 2 additional attacks that do:
10%/20%/30%/40% dmg each +10% with scepter

Don't know if it should be an ult or not.

**Comment by DankBudd** [comment]
drow ult + drow ult(without agi)
would probably be overpowered

**Comment by 01der** [comment]
>drow ult + drow ult(without agi)
would probably be overpowered

but wouldn't it be rather:
drow ult (without splitshot) + splitshot
that you would be able to pick?
so in the end you get the current marksman but for the price of 2 ults and 7 lvls instead of 1 ult and 3 lvls?

**Comment by 1ran-wang** [comment]
I think marksmanship should be troll combo with any other marksmanship.

And I still think marksmanship with grow is a ultimate farming machine(Multi shot won't be disable by nearby enemy heroes.)

**Comment by 01der** [comment]
I haven't noticed 2 marksmanships being that strong, definitely doesn't get picked a lot.
Marksmanship and Grow on the other hand gets picked a lot, because it is very very strong, but i am not sure if it is stronger than some other combos with OP enabled...

**Comment by DankBudd** [comment]
> I think marksmanship should be troll combo with any other marksmanship.

marksmanship str and int dont have splitshot. its just the original agi one

> but wouldn't it be rather:
drow ult (without splitshot) + splitshot
that you would be able to pick?
so in the end you get the current marksman but for the price of 2 ults and 7 lvls instead of 1 ult and 3 lvls?

so with your original post you were saying you want to separate Marksmanship and its scepter upgrade into two different skills? i disagree with this, we shouldnt be changing the base dota skills like that.

i thought the suggestion was to just add the splitshot effect as a skill (like side gunner) and keep marksmanship how it is.

**Comment by 01der** [comment]
> so with your original post you were saying you want to separate Marksmanship and its scepter upgrade into two different skills? i disagree with this, we shouldnt be changing the base dota skills like that.

That is exactly what i was suggesting. And we have changed base dota skills like that already: grow redux, borrowed time redux, chem rage redux. Marksmanship redux would just join as Marksmanship redux.

Right now Marksmanship is banned in OP-off, thats why i suggested these redux skills.

**Comment by DankBudd** [comment]
the difference in the redux skills you listed were just number changes, the behaviors of the skills were not changed.
if a Marksmanship redux was added it would also just be number changes, these are the current values for the splitshot portion of Marksmanship, what changes would you suggest?

    Max Splinter Targets: 2

    Splinter Search Radius: 375

    Splinter Damage Reduction: 50%

**Comment by 1ran-wang** [comment]
I think lower the damage rate into 25% is a good idea.

the difference in the redux skills you listed were just number changes, the
behaviors of the skills were not changed.
if a Marksmanship redux was added it would also just be number changes,
these are the current values for the splitshot portion of Marksmanship,
what changes would you suggest?

Max Splinter Targets: 2

Splinter Search Radius: 375

Splinter Damage Reduction: 50%

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/darklordabc/Legends-of-Dota-Redux/issues/1183#issuecomment-322059664>,
or mute the thread

**Comment by 01der** [comment]
I prefer my original suggestion which is AGI-Marksmanship without Aghs upgrade for OP-off:
Max Splinter Targets: 0
Splinter Search Radius: 375
Splinter Damage Reduction: 50%

And Splinter as a separate skill:
Max Splinter Targets: 2
Splinter Search Radius: 375
Splinter Damage Reduction: 50%

You can call that a number change if you want.
I argue that, that would balance Marksmanship nicely for OP-off and with a nice red tooltip people wouldn't make the mistake of building Aghs with Marksmanship Redux more than once.

We already have heroes that had their scepter upgrade or innate abilities removed into separate skills.
I think the same would make sense here.

**Comment by darklordabc** [comment]
I like the idea of making original marksmanship a single player ability and splitting the ability into the ability bonus part, and the splitshot part, also it would make the other marksmanship more useful because they could get splitshot too.

**Comment by DankBudd** [comment]
started working on this #1201

**Comment by DankBudd** [comment]
Implemented
