### ISSUE TITLE
[Troll combo] Windtrap + techies + caster range boost = perm

### ISSUE THREAD

**Issue by 1ran-wang** [darklordabc/Legends-of-Dota-Redux#1194]
As the title, I could lower the Techies's cooldown perk from 50% into 25% because he already has 20% cdr talent Or make Windtrap's cast range became 300. Which one is better?

**Comment by LoDfan** [comment]
In my opinion it's better to just remove windtrap.

**Comment by darklordabc** [comment]
I made it so that you can no longer be cycloned while u have the armour debuff, the debuff lasts for 8 seconds, so after cyclone u have about 5 seconds of immunity to other cyclone traps, should be enough to end this troll combo.

Also, Techies no longer has his cooldown reduction talent as they have been removed from the game.
