### ISSUE TITLE
Fix players disconnecting during ban phase and being stuck without hero

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1198]
Read here for more info: https://github.com/darklordabc/Legends-of-Dota-Redux/pull/1193

**Comment by 01der** [comment]
I think that part might be the culprit:
https://github.com/darklordabc/Legends-of-Dota-Redux/blob/f300572b2e01753bfece4d2a6490cb60a94476fb/src/game/scripts/vscripts/pregame.lua#L1505

what would be the drawback of removing that?

**Comment by DankBudd** [comment]
that part is commented, it is ignored by the code. it was likely once used but not anymore

**Comment by 01der** [comment]
IDK what the last patch changed, but just a minute ago i had the same problem as always:
drop out at start of banning,
reconnect after banning is done,
no spawn
thx for trying to fix this, but its still broken.
btw its weird that when i reconnect during banning, the builds will just not load, which is good, because otherwise it would probably timeout right away again.
So i still think that changing how the build-loading works, might be the solution.
