### ISSUE TITLE
[bugs] various bugs

### ISSUE THREAD

**Issue by 01der** [darklordabc/Legends-of-Dota-Redux#1205]
Aghs shallow grave doesn't work on dazzle.

lifebreak and treedance seem to have a hard-coded max castrange, they don't go off if you got too much cast range.

**Comment by DankBudd** [comment]
scepter shallow grave doesnt work with dazzle specifically? or doesnt work with anyone?

**Comment by 1ran-wang** [comment]
It doesn't work on dazzle because dazzle's perk actually replaced the
shallow grave

2017年8月17日 上午2:32，"DankBudd" <notifications@github.com>写道：

scepter shallow grave doesnt work with dazzle specifically? or doesnt work
with anyone?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/darklordabc/Legends-of-Dota-Redux/issues/1205#issuecomment-322981492>,
or mute the thread

**Comment by LoDfan** [comment]
Confirm that. But I think this perk it too OP with CDR build. Dazzle still can give some ally hero perma buff of SG being on fountain. So in my opinion it's better to change his perk. May be it's better to increase Shadow Wave heal/dmg?

**Comment by darklordabc** [comment]
Dazzle perk has been changed. He no longer gets a modified shallow grave, this fixes the perma buff issue and also the issue of it not working with scepter, please close this issue if its done.

**Comment by darklordabc** [comment]
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/6687c3a7c8baef84fce444a393a82afb056f9450
