### ISSUE TITLE
Overpowered combo Tether + Arcane Symbiosis + Heart of Tarrasque

### ISSUE THREAD

**Issue by ReactorXIV** [darklordabc/Legends-of-Dota-Redux#1211]
If you pick Tether and Arcane Symbiosis and then you buy a Heart of Tarrasque then your host has insane amount of healing from your Heart of Tarrasque. I would suggest to make is so that Heart of Tarrasque is disabled when your host is being hit.

**Comment by darklordabc** [comment]
@DrTeaSpoon could you make the heart and dagger go on cooldown when the host is attacked?

**Comment by DankBudd** [comment]
also tranquil boots for the sake of consistency

**Comment by LoDfan** [comment]
I want to pay attention on this troll combo. It's really OP.

**Comment by darklordabc** [comment]
This has been semi-nerfed. Symbiotes can still cast tether on their host, but now tether will have a 60 second cooldown, instead of 12 seconds, so they cannot constantly have the health regen active. 
https://github.com/darklordabc/Legends-of-Dota-Redux/commit/7a4c8a18d7582abf6a70dba5654a488e900a6eed

I didn't want to completely nerf the combo, as its kind of creative.
