### ISSUE TITLE
[Suggestion] Adaptive strike for strength and intelligence

### ISSUE THREAD

**Issue by fumyk** [darklordabc/Legends-of-Dota-Redux#1225]

**Comment by DankBudd** [comment]
regular adaptive strike uses strength to measure stun duration, and agility to measure damage. 
how would the strength and intelligence versions measure damage and duration

**Comment by fumyk** [comment]
i think both adaptive strikes can use agility to measure stun duration

**Comment by Fapboard** [comment]
Nobody really cares about regulations for the minor details.

Back in my previous community of lodding, adaptive strike was just given a flat stun duration and giving a base damage + 2x Primary attribute in damage to a target.
 - Pushing was also removed in the process.

If nothing else gives, theres a method for you to use.

**Comment by darklordabc** [comment]
Yeah i rekon just use strength as stun duration for all of them.

**Comment by darklordabc** [comment]
If somebody want to makes these i'll merge them

**Comment by 1ran-wang** [comment]
So Ultra str build with str strike will become troll combo ?

**Comment by DankBudd** [comment]
so since volvo seperated adaptive strike into 2 skills, one for agi and one for str, this issue should now be about making a int adaptive strike, yeah?

i could implement this but..
what kind of effect should the int strike have? agi does damage, str stuns..
so int applies magic resist reduction maybe?

thoughts, anyone?

**Comment by Lemurple** [comment]
Perhaps the int version could have a higher cast range?

**Comment by DankBudd** [comment]
thats not really an effect. i guess it could have higher cast range, but what would the ability actually do.

**Comment by Lemurple** [comment]
What I mean is its like a weaker version but has a higher cast range. I.E. the damage is lower and so is the stun but with more range

**Comment by DankBudd** [comment]
adaptive strike agility only does damage. no stun or knockback.
adaptive strike strength only does stun+knockback. no damage.

so you're saying to make the int version have the effects of both the other versions, but weaker.

**Comment by 1ran-wang** [comment]
what about produce mana drain and movement slow?

2017年12月5日 上午5:38，"DankBudd" <notifications@github.com>写道：

adaptive strike agility only does damage. no stun or knockback.
adaptive strike strength only does stun+knockback. no damage.

so you're saying to make the int version have the effects of both the other
versions, but weaker.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/darklordabc/Legends-of-Dota-Redux/issues/1225#issuecomment-349264765>,
or mute the thread
