### ISSUE TITLE
[feedback] 3 Passives

### ISSUE THREAD

**Issue by 01der** [darklordabc/Legends-of-Dota-Redux#1238]
I don't know why we are trying this setting, but if it is to diminish right click builds, then it is failing.
I liked the balanced build gold, because i liked people in my team not being full passive, because in my experience full passive < passive with some active.
I actually dislike the current setting, because it makes it harder for me to pick antistun (counts as passive), which was my goto to counter the stunlock builds which are still thriving (focusfire and chemrage being actives the current setting actually makes them more attractive).
There is plenty of active abilities that don't belong in a caster-build and they are getting picked left and right.

If we want to have less right click builds, i think we have to accept that the problem is:
casters often don't farm as well (and with increased xp and gold bounty farm = win even more)
casters often don't push as well (and with rooting, silencing, manaburning towers it doesnt make it easier)
casters often don't scale as well (and with people having 6 slots by 30 min you have to have some scaling dmg or you wont be able to carry/push)

I think if we want to empower casters we have to go a different way:
buffing caster skills and items and coming up with good caster perks

</feedback>

**Comment by LoDfan** [comment]
I agree with 01der in some cases. Also I would like to add:

- There is only 1 consumable item for casters when there are more than 5 for rightclickers, may be it's better to make aether lens also consumable? May it's better to limit consumable item quantity by 2, so it will be 2 items for rightclickers and 2 items for caster and even 2 items for tanks (heart and AC)
- Greevil's Greed is returned to usual skills and it's very bad. It's possible to make farm range splash build which will have 10 items on 30 min
- Anti physical attack ward is too week. I have a suggestion: make it destroyable only by magic damage (as pugna's ward is destroyed only by attacks) so this ward will return damage till it's destroyed by some magic. HP should be 500-600 so 2 regular cast abilities (target and aoe) should destroy this ward
- There is anti magic buff for a tree. It will be very good to add some kind of anti attack buff for a tree so it'll stun and deal damage to every unit attacking in XXX radius around the tree
- There are not too much perks good for caster like there are very lot of strong perks good for rightclickers. I'll spend some time to make a very long list of suggestions to replace most of under-powered perks.
But ideal balance between physical and magical dps is impossible because of magic is more useful on early phase (there are only some casters builds which do % of hp damage)

**Comment by Techmind** [comment]
consumable aghs like in dota imba would be fine, and even if y can 28-0 enemies as mage, they jsut push way better, os maybe make towers non magic-immune ?

**Comment by darklordabc** [comment]
I think people in this thread are right, that we need to empower casters, but in regards to 3 passives, for now I don't think we should remove it. It has gotten a lot of mixed reactions, some people hate it, but some people have said its good for the balance of the game and of the few games I have played with it on, it has _seemed_ to be more balanced, so I'll keep it on for now, but I hope to make it optional for the dota map soon.

@LoDfan a lot of good suggestions, and I think we should work on them one by one. I've buffed the anti-physical attack ward, and we are working on a consumable aether lens now. You think Greevils Greed should not be pickable? Also I'll check out your perk list too.

**Comment by LoDfan** [comment]
Greevils Greed gives you very easy way to buy 6 slots + 7 consumed which are very good foe any rightclicker build. And I have 10 of 10 game winrate when I picked Greevils Greed. Mostly it was sven or agi long range splash attack build. When your enemies have only 5 arts you have 6 + 3 consumed.

**Comment by darklordabc** [comment]
@LoDfan is'nt making greevils greed a single player ability a bit drastic? There is lots of OP abilities arguably better than greevils greed, like bash and fury swipes.

**Comment by LoDfan** [comment]
Ok, may be.

**Comment by Fapboard** [comment]
TD:DR response on this topic.

I've noticed this feature makes games less lazy in terms of gameplay and therefore choose to use it, despite it forcing a certain meta with people always having active abilities (and hence other abilities takes use of that) instead of simply having free will and not being punished for that free will.

With people being adjusted to lack of passive limitations they just simply begin to slack from gameplay perspectives, regardless of skill.

The downside is naturally that some abilities simply now becomes overpowered in comparison as a result of this and alot of builds are hampered despite being non-rightclickers.

Usually though, this doesn't stop people from rightclicking anyway, since they will get the more pick-worthy passives and a stun instead and bypass the passive limit with powerfull steroid skills like Chemical Rage.

- Regards, Whiteboard.
