### ISSUE TITLE
Rework Originality

### ISSUE THREAD

**Issue by Wouterz90** [darklordabc/Legends-of-Dota-Redux#1241]
Or better said remove it, all it does is punishing long time players because they will have less abilities to choose from. I think the idea to hurt players who make the same build every game is great, I doubt this is the right way to do it though.

What I am proposing is only for viable for points mode, but I don't think there is any point in balancing around the other modes since they are imbalanced by definition.

The idea is simple, apply simple economics to the pick screen. A skill gets selected, that means it is good and should increase in value. If a skill doesn't get picked, it will decrease a little ( I think that should be based on the count of all abilities) in the next game. This will make playing the same build nearly impossible because of the increased cost and will refresh the meta, because certain skills will rise and others drop.

I'm pretty sure this won't be a perfect system either, but it gives an equal playing field for everyone and it the game will balance itself, even when nobody cares about changing the values. If I'm overlooking something, you got an improvement to this, have an opinion please give it to me!

**Comment by SwordBacon** [comment]
The Grand Exchange: Redux. I support this 100%!

I would love to spend some time on this actually, it's a very simple and elegant solution to repetitive builds. Any points remaining could be converted into bonus starting gold too. 

As an extension of this idea, we could record stats regarding trends in ability selection, as well as saving player data regarding all skills they've picked across games. The more stats we record, the more potential to reward longtime players. We could build a whole achievement system around this idea.

**Comment by russo-2025** [comment]
I completely agree
P.S. translate google

**Comment by LoDfan** [comment]
I like the idea because current system is not good for long game history. My ideas are different, but they may be used without points mode and are very simple to implement:

- ability picked in last 3 games by player A is banned in current game for player A, other players are able to pick it. Next game player A will be able to pick  these abilities
- a little fix for current system: save only history of last 10 games so players playing very lot won't receive less money at start comparing to newbies

**Comment by Wouterz90** [comment]
I revived SwordBacon? 🔪 🥓 

LoDfan, you suggestions seem to be unrelated or am I wrong?

**Comment by LoDfan** [comment]
Your proposition was only for points mode. And I suggested changes which will be good for all allowed mode (which is default one).
But for points game mode your suggestion is perfect.

**Comment by 1ran-wang** [comment]
I'm totally agree this. the current system is so unfriendly to old players.

>

**Comment by SwordBacon** [comment]
@Wouterz90 yup, pork knife is back 👍 

The thing about your suggestion is that it wont require a butt-ton of work like implementing hero perks was. We just need to plan out the formula for calculating/updating point values for abilities based on selection and work with a database.

**Comment by Wouterz90** [comment]
I think it should something like this right?

https://docs.google.com/spreadsheets/d/1yQQVz59T_xtNfpsX4gUnGtuI61J_Qz-vTuv7ZdSj0DU/htmlview

**Comment by darklordabc** [comment]
> What I am proposing is only for viable for points mode, but I don't think there is any point in balancing around the other modes since they are imbalanced by definition.
Unfortunately, players don't like points mode, even tho we may think it's a superior system. I've opted to allow players to pick 'all abilities' but have more subtle balance mechanics, as opposed to the more obvious mechanics of points mode. I think the way forward is working within.

Your suggestion is a good idea for a general improvement to points mode, but since it doesn't get used much, I'm not sure it will be worth the investment. 

> The idea is simple, apply simple economics to the pick screen. A skill gets selected, that means it is good and should increase in value. If a skill doesn't get picked, it will decrease a little ( I think that should be based on the count of all abilities) in the next game. This will make playing the same build nearly impossible because of the increased cost and will refresh the meta, because certain skills will rise and others drop.

The current system already has a version of this mechanic. It tracks which abilities are most popular, and awards a bonus to players who pick unpopular abilities, unpopular abilities are those that are not in the top 25% of selected abilities. 

I like @LoDfan's idea of making the ability tracking have a short memory so that it only counts the last x amount of games, I think that is fairer to long-term players. 

@SwordBacon I know we do have some statistics somewhere in the web, @ark120202 set up the server, we keep track of which abilities players have used and a number of times they have used them and based on that info we determine which are the most popular abilities. 

Perhaps we could make changes to the bonuses. Like perhaps remove the new ability bonus altogether, And just have tiers of popularity gold bonuses. So top 25% gets no bonus, next 25% get a small bonus, next 25% get medium bonuses, and the lowest 25% of abilities get the highest bonus.  This will be workable in non-points mode, but will also introduce more elements of the "The Grand Exchange".

**Comment by Wouterz90** [comment]
Is points mode dead because the all_allowed and standard don't include it, or because people don't pick it in the dota version?

**Comment by DankBudd** [comment]
i imagine its because of all_allowed not including it. last 2 or 3 times i played dota map the hosts enabled points mode.

**Comment by LoDfan** [comment]
Dota map is not popular because it's not default one and it uses old ability pick phase which causes a lot of dcs.
In my opinion the default map should be some official like map without custom skills because official outdated version of lod is still created by Asian players and some EU players. A lot of players don't want to learn what to do with custom skills and I saw very lot of leaves after being killed by some custom skill. But I know my opinion is not very popular because most part of players vote OP and custom abilities.

**Comment by russo-2025** [comment]
I also would like to see default map without custom abilities. Custom abilities still have a lot of imbalanced skills which can't be cowered only by 3 bans.

**Comment by darklordabc** [comment]
I don't know about this, I think lots of players want the custom abilities. Not sure if this will be a good idea to remove them.

**Comment by LoDfan** [comment]
I advice to check how many players still play outdated official LoD and how many players play LoD Redux with custom abilities. They still play game without talents and 2 critical bugs (leshrac's ult and gyro with infernal blade). I don't understand such players but I think they don't want to learn nearly 100 new abilities.
