### ISSUE TITLE
Aether range (skill)

### ISSUE THREAD

**Issue by russo-2025** [darklordabc/Legends-of-Dota-Redux#1258]
"Aether range" увеличивает дальность применения  некоторых способностей автокаста.
Aether range" increases the range of application of some abilities of the autocast.

P.S. Aether Lens, Talent(Сast Range) do not increase.
P.S.S. translate google.

![20171001225714_1](https://user-images.githubusercontent.com/28739948/31058750-6881e472-a701-11e7-88c5-0813dd0139af.jpg)
![20171001233559_1](https://user-images.githubusercontent.com/28739948/31058745-579fc656-a701-11e7-99b3-39aff69eb41d.jpg)

**Comment by YURNER0** [comment]
это только часть багов/странностей, которые я заметил.
this is only part of the bugs/oddities that I noticed. 

P.S. translate google.

**Comment by darklordabc** [comment]
This is interesting but I don't think its necessary a problem, it can just be an extra perk for aether range. I've updated the description of aether range so that all players can be aware of this mechanic https://github.com/darklordabc/Legends-of-Dota-Redux/commit/02cadb5ab4ea24b57fa62c4f874f37e480792256
