### ISSUE TITLE
redux multicast lvl 2 fix

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#1324]
Hallo i found an incorrect multicast chance setting in spellfixes file i think there is missing 0 after first number. I tested it and it looks like was right because when compared lvl 1 with lvl 2 lvl 2 seems to be weaker than lvl 1  i also looked into spellfixes from Ash. I think it should be like this:

                            elseif lvl == 2 then
                                if r < 20 then
                                    mult = 3
                                elseif r < 40 then
                                    mult = 2

**Comment by Fapboard** [comment]
Confirmed.

While ingame for maximum efficency, I used to save a skill point to level it up twice from 1 -> 3.

Level 2 of Multicast Redux procks about once every 5 games you play, instead of its regular value according to tooltip.

So instead of it's supposively 20%, it has 2% prock chance because of a typ'o.
