### ISSUE TITLE
Gamemode deleted?

### ISSUE THREAD

**Issue by XAgent1990** [darklordabc/Legends-of-Dota-Redux#1325]
The gamemode is unable to be played and nowhere to be found in the Workshop.
People are starting to "blame" Ash47?!
What happened? D:

**Comment by Ralayax** [comment]
I hope this is not the end.
If it's the name "Legends of Dota", maybe you could just rename the game mode just "Redux" ?

**Comment by XAgent1990** [comment]
renaming it wont change anything about the fact that its just copied without the original maker wanting that.

**Comment by Ralayax** [comment]
So many things are copied, like isn't LoD almost exactly ability draft ?
KDE Desktop looks like windows, samsung phones are almost exactly as iPhones.
If copy was always prevented there would be no progress..

Redux has so many features, is actually open source.
The real problem would be if some code was actually just copied, so the question is "is it the case ?".

**Comment by Fapboard** [comment]
Frankly put, Lod Redux is bigger than our developer.
 -  I certainly didn't come here for darklord or any other dev, I came for lod.
Many people are missing it since developers are behaving like 5 year olds with their imagination protest.
Down to the punchline, fuck the details and get it uploaded again.
 - Without the devs if that's what it takes.

Fuck we'll have (a) new developer instead. Perhaps someone who cares about the mod and actually tests stuff out himself to see if things checks out properly.

**Comment by Ralayax** [comment]
Well, speaking without knowing anything of what happened (so feel free to just ignore), if Ash47 has been aggressive to darklord, I can understand darklord not wanting to go on with redux..

**Comment by Fapboard** [comment]
If the post he made is to be taken for truth, ash47 is litterally fucking with everyone.

Thats it.

Thats all there is to it.

And the playerbase of lod redux is punished unesc.

And if thats the case, I say fuck the devs.

On the topic of darklord:
 - He's a big boy who can make his own decisions (if not, that's pathetic and hopefully not the case), if he chose to go along with this then he's anti-lod basicly. For having a "protest" with no demands mentioned or even an official statement, plain retardism.

Map is down, developer hasn't said a word.

Time to just simply take matters into our own hands.

I beg of you, any compentent modder in this format to just simply copy-paste the mod and have it up and running again, I couldn't care less about others pettiful disputes that they'r having in their own duckpond.

It's about Lod Redux and it's down in a completetly uncalled-for; manner.

Have it up and running and you'll have my grattitude amongst many others, plus we can play lod redux again.

- Regards, Whiteboard @Discord.

**Comment by Fapboard** [comment]
Also i'll leave this thread with this regarding a copy-paste of LodR with new dev(s).

There's 2 possible scenarios playing out here.

"Worst case scenario": Devs gets it up and running again and we can simply smoother over the missunderstanding and in the meantime we got LodR and take it down once they resume the project once again.

"Other worst case scenario": They are never heard from again and the project is inofficially down and we proceed having LodR up and running without them.

Since no one said shit, i'll presume it's down permanently or just a prank.
But regardless everybody wins no matter which outcome.

**Comment by Angellorus** [comment]
Now the gamemode is unplayable, yup definitely dead

**Comment by XAgent1990** [comment]
it was unplayable before

**Comment by DankBudd** [comment]
reuploaded until darklord comes back (if he comes back) http://steamcommunity.com/sharedfiles/filedetails/?id=1255088739
