### ISSUE TITLE
option to pick skills for Spirit Bear / Towers

### ISSUE THREAD

**Issue by Undead772** [darklordabc/Legends-of-Dota-Redux#1326]
Hello, as far as I remember in the old version it was possible to choose skills for _summons_ (Bear, wolves, etc.) could you add this opportunity, I would **really like to see** it!

**Comment by Fapboard** [comment]
A huge variety is allready available from the summons ingame to the drafting pool.

In order to be of any of help, youre going to have to be more specific of what's missing or ought to be featured.

**Comment by DankBudd** [comment]
hes talking about giving skills to spirit bear.

it was a old somewhat hacky feature in the original LoD. but ash removed it along with the 12 ability slots option in early dota reborn days.

i believe it was removed because of its hacky nature and incompatibility with bots.

**Comment by Fapboard** [comment]
Fuck the bots.

If it's doable (completly ignorant of this hacky nature part you speak of), i'd say put it in the game again as an option.

**Comment by Undead772** [comment]
I just played one of the old versions of the Legends of DotA, I remember that when you choose summon, for example, a druid bear or a wolf, they could be given skills.

**Comment by Fapboard** [comment]
Since you replied again:

That's a really cool concept and i'll repeat myself: Put it in the game as an option.

**Comment by Lemurple** [comment]
Oh hell yeah we need this, theres gonna be some strong combos that go with it

Also as you mentioned the 12 skill slots id like to see that too

**Comment by darklordabc** [comment]
This is a bit tricky, as it requires reconfiguring the ability screen layout, and it seems like quite a bit of work for a niche thing which is probably going to be OP either way. Not sure if its worth the work invovled.

**Comment by Fapboard** [comment]
Basic idea for having this implemented:

- Bear ability bar: If you have selected Spirit Bear in your editor/drafting screen another skillslot panel unfolds below where you may click, drag and delete abilities with <6> abilities in total between the 2 panels.

- 12 skill mode: if 12s is enabled as mod -> expand skillslots layout to 12 or utilizes the new supposivly unfolding panel but the abilities in that row applies to your hero instead of bear (unless bear is selected, then 3 slot panels in total are available to modify at your disposal.).

The coding though I cannot speak of/for as I dont personally code in this envoirment.
