### ISSUE TITLE
Problems with the Panorama shop

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#1336]
- [ ]  **purchase delay**
 theres a delay when buying an item that is significant enough to cause you to buy multiples of the same items from quickbuy when you have multiple items in quickbuy

- [ ] **items always sent to stash**
currently any purchased items will be sent to the stash instead of your inventory, regardless of if your hero is in range of a shop

- [ ] **items that require stock never gain stock**
so they never become purchasable again after the initial stocks runs out

- [ ] **secret shop items can be purchased anywhere**

- [x]  **AABS items are still available dispite being 'disabled'**
they can be searched for and can be found in item build ups

- [ ]  **lost conveniences**
     1. ESC key to close shop
     1. CTRL+(set quick buy) to set multiple items

**Comment by darklordabc** [comment]
@ark120202

**Comment by darklordabc** [comment]
Thanks for this list

**Comment by Acture** [comment]
I noticed that sometimes I'm not able to cast spells or moving heroes if the new store is open.
Also, is there any way to keep the new items visible in the store? It's so easy to miss something like Aether Lens.

**Comment by darklordabc** [comment]
I can't reproduce the purchase delay. @Acture @DankBudd, how common is the purchase delay? Every game or rarely?

Items brought to stash, @ark120202 can fix that. 

Just tested. Can confirm that stock items do not replenish nor do they show any graphics or cooldown or timer.
![image](https://user-images.githubusercontent.com/16277198/35254249-9094e0fa-003d-11e8-8a4d-759603f80ac3.png)

Secret shop items being able to be purchased anywhere, is because universal shops are on, and this was a sacrifice made for having Panarama shops. We will look into this again maybe there is a way we can have it like normal.

AABS items were still active, ops, I've properly disabled them here https://github.com/darklordabc/Legends-of-Dota-Redux/commit/a327c95078a99e64901291fe446ea045a13753e4

Lost conveniences, we will look into, may not be possible to bring those binds back. 

Another problem unmentioned in OP is that clicking on the shop keepers does not open the shop tab.
![image](https://user-images.githubusercontent.com/16277198/35254310-c72c5e40-003d-11e8-99c4-7d1e4eeacc7d.png)

**Comment by Acture** [comment]
I got purchase delay every game since the very beginning of the game.

**Comment by darklordabc** [comment]
Is it dependent on the ping of the game? Or do you get it even in games with low pings?

**Comment by Acture** [comment]
Nah. Everything else is fine. If I got a high ping, I should also notice the delay in movement. I don't remember my exactly ping number, but I think it wasn't high.

**Comment by Acture** [comment]
Hmm, I played again several times. And the purchase delay problem seem to be fixed

**Comment by darklordabc** [comment]
Well let me know if it returns please

**Comment by DankBudd** [comment]
i still get the purchase delay, but it does seem to be less significant now. which is strange because it hasnt been changed.

maybe it has to do with my shitty pc, since the JS code is running on the client (my pc), rather than volvos server.

**Comment by Acture** [comment]
I got purchase delay several times these days as well. And I agree it's less significant. 

I guess it's not something about your pc. My pc has 7700k, gtx 1070, and I still get the delay.

**Comment by darklordabc** [comment]
I'll try to disable the shop for now.
