### ISSUE TITLE
Flesh Heaps work on Reincarination

### ISSUE THREAD

**Issue by Acture** [darklordabc/Legends-of-Dota-Redux#1339]
It seems that those flesh heaps works differently from the original one. If I pick one of those new flesh heaps with the original one, I'll probably get different stacks for them. One thing I've noticed is that I can get stacks from reincarnation. Another thing is (I'm not sure about this one),  if I'm in the 450 range and get the kill, I will receive two stacks for that. Not urgent though.

**Comment by DankBudd** [comment]
which flesh heaps are you talking about? all of them?

i was unable to replicate getting 2 stacks for killing someone who is also within the 450 range.

however i can confirm reincarnations give flesh heap stacks. it shouldn't do that.

**Comment by Acture** [comment]
all except the original one. Kind of sure the one before the previous version has the problem. Not sure about this patch

**Comment by Fapboard** [comment]
Indeed, the original flesh heap has specificly written in it's tooltip to gain a stack on a hero kill or if it dies in your vicinity, not both.

Regarding reinkarnation, it might be intentional - this should be checked if the str heap triggers from that. And if it does, i'd  say keep/let the custom heaps proceed as such (as its confirmed that custom heaps gains stacks from slain enemies while having a custom heap).

Ontop of this topic of correcting heaps beaviours I also want to suggest making custom talents for the custom heaps to gain additional bonuses as the original flesh heap does.
