### ISSUE TITLE
Survival of the fittest skills are a mess.

### ISSUE THREAD

**Issue by Fapboard** [darklordabc/Legends-of-Dota-Redux#1372]
Those abilities were not well thought out nor implemented and essentially just kills games.

You only have 2 scenarios regarding these abilities:

1: The person gets his way and never dies.
2: He dies at somepoint by something random and unpredictable in the game.

Then as you might expect, the ability does nothing, litterally nothing and will never do it's outmost for that game thus ending it for that player, probably affects his team as well as a result.

Both for the player himself, the team and the opponents it's boring to have this "Risk it all dude" in the game and only RQ's when his attempt has failed in the second and most frequent scenario.

And I can't imagine scenario 1 being better, while being a onesided interaction for the entire game for the other team.

This ought to be looked into and corrected.

- Regards, Whiteboard.

**Comment by ForbiddenFruitPOD** [comment]
I think suggest the following:

-upper limit on stacks of survival of the fittest (prevents getting super OP from never dieing)
-death removes a percent of current stacks. (prevents losing everything from an unlucky/random death)

**Comment by Fapboard** [comment]
Indeed.

If these abilities are to have an upper limit, the rate you aquire stacks ought also to go up, thus giving you a "prime time" of when you are most effective/powerful.

The beautiful part of losing a percentage instead of all stacks on death, would allow the game to be more back-and-forth hence more interactive game for everyone.

I would also consider having a base value for these abilities for 2 reasons: Giving you a starting value and a reason level it early and if dying, you still got something to fallback on instead of having a wasted pick from draft.

- Regards, Whiteboard.

**Comment by ForbiddenFruitPOD** [comment]
I think a good system to follow is this:
initial /minimum value = 50% of comparable abilities
max value = 150% of comparable abilities
time to reach max value = 15 minutes
Death reduces remaining stacks by 66% and does not reduce stacks to below initial value

Maybe 50% is too much, I'm not sure, but either way in order to incentivize using the survival skills, their max bonus must be greater than that of comparable abilities. The trade off is that comparable abilities give the bonus right away and doesn't change with death, so there must be a reasonable reward for the risk of choosing the survival skills.

Example using "survival of the fittest - attack range" (SOF-AR) and "Take Aim" (TA) at level 4. Currently TA at level 4 gives 400 range. SOF-AR currently provides 20 range per minute, so it needs 20 minutes to be equal to TA, which is too much IMO. 

New SOF-AR should be as follows (at level 4):
- initial range bonus = 200
- maximum range bonus = 600
- gains 26.27 range per minute until 600 range

Similar modifications can be done with "Survival of the Fittest - Spell Amp" and "Books of Knowledge" or "Survival of the Crittest" and "Blade Dance" as other examples.

**Comment by Derpboard** [comment]
Personally i'm somewhat against having an upper limit with this branch of abilities since it kinda goes against the original concept, much like the Heaps of various sorts. It's supposed to be unlimited power.

What could be done is lowering how much you get for free over time and simply implement "get-stacks-on-creep kills" mechanic which will encourage risk taking at your own disposal while giving these abilities base values as previously mentioned.

And ofc having the bloodstone princip applied here with (your suggestion which will do fine) 66% loss of all stacks on death.

Should be taken into consideration ofc before any hasty decisions are made, topic is prone towards further disccussion.

*Previous details weren't half bad.

- Regards, Whiteboard.

**Comment by OtsoTurpeinen** [comment]
What would you think of multiplying the recovery rate to the highest stackcount so far. Not sure how fast.
double or triple the stack gain rate?
so if you have gained stacks for 15 mins and you die. You would gain those stacks back in 5 or 7.5 mins and return to normal rate.

**Comment by CaptainDildac** [comment]
The original survival of the fittest ability was multipurpose, it provided a larger hp regen bonus coupled with a smaller mp regen bonus. This was not the only thing it did however; it also had ALT-info that stated it allowed the passive holder to ignore the movement speed cap. It had a decent niche for non-thirst speed builds(this is also back before movement speed cap was re-balanced). I think the bonuses need to be coupled with some base-line non-scaling static bonus that is unique enough AND makes sense with w/e survival stat type its attached too. On the other end of the coin, this is also more work to do for an arguably already finished group of abilities that is functioning EXACTLY how it was intended during a time when the game needs a TLC update for random little things that have been building up over time. 
As a side note, most qualms with the ability come from players picking it and leaving because they cant handle the gamble they just lost(when or if they die). Unfortunately if you can't handle the gamble and run away when your hand loses you the pot, then these abilities are perhaps not for you. You gotta pay for it somewhere and that gamble IS the fulcrum from which those stacking stats are given to you.

**Comment by darklordabc** [comment]
I like your idea @OtsoTurpeinen of having a double recover rate to your highest achieved stack. It gives players an incentive to stay alive and get a higher stack but at the same time offers some redeeming feature if they do die. I think it should be double tho, triple is a little to helpful.

**Comment by darklordabc** [comment]
They have been modified to have double regen after death, Otso's idea.
