### ISSUE TITLE
Souls spells balance.

### ISSUE THREAD

**Issue by Techmind** [darklordabc/Legends-of-Dota-Redux#1414]
Some of them quite OP, almost free 200 str/agi/hp regen (200 int is only 10% magic resist so not that OP, only matters for OD anyway).

This is necromastery on steroids. Which is limited by 32 dmg/46 dmg with aghs. Maybe they should be rebalanced to give less + require aghs to reach 250.

**Comment by Techmind** [comment]
1 creep wave gives almost 4 str/agi/whatever. And y have camps and creep count increases during the game.

**Comment by Techmind** [comment]
Also: souls attack range is broken OP on melee heroes, allows 25% basher, 0 projectiel travel time. And its very easy to get +250(*5)=+ 1250 range on fast-attacking heroes, or on someone with mobility to clear jungle + lines, basicly 100 soul(+500 range) is enought to snowball, by stun-locking/stacking MELEE essence shift/ursa claws, etc. 
It should be maybe 1/2 per soul max.

Current attack ragne souls is better than psi blade + take aim skill, which is considered troll combo.

**Comment by ForbiddenFruitPOD** [comment]
I think the balance between lingering souls and related passives needs to be addressed as a whole. Here are some examples of balancing issues with lingering souls:

-Lingering Souls Damage vs Necromastery: Advantage of lingering souls damage is being able to provide more damage (+375, compared to 180 of necromastery, with talent). Necromastery is much safer as only 36 kills are needed to max the bonus, and half of them are kept upon death, compared to losing 250 stacks of Lingering Souls. I think that Necromastery should be buffed to close the gap between these 2 skills, but ultimately lingering souls should provide a bigger bonus as it has a bigger risk. I suggest that Necromastery should provide +4 damage per soul (+6 with talent) compared to the present +2 per soul (+5 with talent).

Note that I am not considering the scepter upgrade into this comparison as it is just Lingering Souls attack damage vs Necromastery, not Lingering Souls attack damage vs Necromastery + 4200 gold. With that logic I can say Lingering Souls Attack Damage + Desolator vs Necromastery + Scepter.

-Lingering Souls Spell Amp vs Books of Knowledge: books of knowledge provides 20% spell amp but cant be lost if you die. Lingering souls spell amp provides 25% but  you can lose it if you die. I think books of knowledge is better, that extra 5% isn't worth the risk imo. I think buffing Lingering Souls spell amp to 30% would make it worth the risk.

-Lingering souls attack range vs Take Aim: Lingering souls attack range > take aim. 1250 > 400. Lingering souls attack range should be nerfed to provide extra 700 range at max level. This is actually so OP, especially with impetus and ranged melee builds.

-Lingering Souls attribute vs Brawler/Marksmanship: strength and agility versions of Lingering Souls are fine, intelligence version should be nerfed to be the same as strength and agility versions.

-Lingering Souls Cast Range vs Aether Range: lingering souls cast range provides +2500 cast range at max level compared to +500 from aether range. Lingering souls cast range should be nerfed to provide 900 at max level imo.

 -Bonus: Lingering Souls Armor vs Survival of the Fittest Armor: 1 armor per kill vs 1.6 armor per minute. In order to get 32 armor, its 32 kills from lingering souls or 20 minutes from survival. 32 kills is much much easier to get than staying alive for 20 minutes.

**Comment by OtsoTurpeinen** [comment]
-Changed Souls Int from 0.75 to 0.5 (max 125)
-Changed Souls Spell Amp from 1.0 to 1.2 (max 30%)
-Changed Souls Attack Range from 5 to 2.4 (max 600)

**Comment by Techmind** [comment]
I would say that int is most useless stat from primary stats (couple of % mana resist if primary) so marksmanship int, survival int and souls int are not that great and could use a buff actually. Having more hp(even without status resistance) and more armor is way better, that having 5-10 % magick resist (basically worth ~500 gold, same as hood).

The only use for int in right-click builds is od/silencer orb. And od orb with essence aura is better than int marksmanship/souls/survival against heroes and creeps anyway.

So nerfing souls int was not required.

Also souls dmg gives 1.5, which is way better than necromastery. And necromastery REQUIRES talent. You can get +36 dmg with 1 lvl of souls by killing 24 creeps. So it is way better, also y can bank charges (you keep 250 if y had 500+ for example) for souls. So it is way better.

**Comment by DankBudd** [comment]
clearly youve never seen proper use of 'mana shield' or 'whiteboards revenge'

int is the least useful stat on its own, but as a result of that the skills that make use of int are generally stronger than the skills that make use of the other two stats.

**Comment by Techmind** [comment]
Nope, they are not that good, whiteboards revenge does nothing vs other mages. And any non int-hero 
1) can use bkb
2) still have 0.25 attack speed, so 1 in 4 hits ignores that passive. Yeah 1st hit can hit for 1000-3000 magick dmg IF enemy had lingering souls int and y had 0 items/passives for magick resist, BUT blademail will delete enemy  himself from 1 hit and will delete 2/3 or all his int from passives.
3) mana shield does not matter, if y cant damage enemy yourself. And attacks in melee = 50% of time you are bashed + 25% walrus punched.

I saw correct usage of whiteboards revenge once and i was playing mage myself against this other hero.

Is there any stat collection after game ? Maybe we should just nerf skills or group of skills which give 50+ % win rate ?

**Comment by Techmind** [comment]
Souls armor - should be around 40 max as dragon knight`s passive * 2.

**Comment by Techmind** [comment]
Also mayeb up cooldown a bit to 30-35, cause no point in taking it -> octarine is better, cause it is consumable and they dont stack.
