### ISSUE TITLE
Fountain farming is back (dispersion + souls armor).

### ISSUE THREAD

**Issue by Techmind** [darklordabc/Legends-of-Dota-Redux#1423]
Subj. Picture - https://imgur.com/a/vHJHU
My linux bugged during print screen so picture is quite dark.

Solution: 1) nerf souls armor, 2) make fountain have pure dmg (and hit for 3-6k, so someoen can tank at most 2 hits) 3) make fountain disable passive on hit(so no dispersion)

Also i can ward uphill or use kotl/ns+aghs near fountain and attack with +range/skills talents.

**Comment by DankBudd** [comment]
the combo i see being used there is not dispersion + armor, its dispersion + overcharge.

they are infested with a dazzle using tether + overcharge.
dispersion giving 22% (30% with talent) damage reduction, and overcharge giving an additional 20% damage reduction.
so that vengeful is taking only 50% damage from all sources, before any other kinds of reduction.

that said, its been suggested before that the fountain apply a break aura and i fully support that. #997

**Comment by Techmind** [comment]
He would not survive 140 stacks of overpower without that armor from armor souls: the problem this 50% damage reduction + 50% damage reduction from phys from armor make him invulnerable to fountain and  50% dmr from phys dmg cant be lowered by fountains essense shift.

**Comment by DankBudd** [comment]
damage reduction and damage reduction from armor doesnt stack additively.

say they are taking 200 damage, first the damage reduction from sources like dispersion is applied (50% reduction)
`200 - 200 * 0.5 = 100`
and they only have 30 armor in that picture, meaning they would get 64.29% further reduction if the damage type is physical. [armor formula:](https://dota2.gamepedia.com/Armor#Damage_multiplier) `1 - (0.05 × armor ÷ (1 + 0.05 × |armor|))`
`100 - 100 * 0.6429 = 35.71`


but we arent dealing with 200 damage, they have 147 fury swipes stacks. *(actually 143 but i already did the math for 147)*
assuming that the fountains fury swipes are max level that is 4410 damage.
`4410 - 4410 * 0.5 = 2205`
`2205 - 2205 * 0.6429 = 788`

so they *should* be taking 788 damage per fountain hit assuming they dont have any other sources of damage reduction.

even if the armor value shown in that picture is somehow wrong, and they actually have an additional 250 armor from the souls skill, it wouldnt make much difference due to diminishing returns.

but obviously thats still a very high amount of damage, so i would have to assume that either the infested dazzle has some skill like shallow grave that was keeping the vengeful alive, or they are somehow giving the venge an absurd amount of health regeneration via tether.

**Comment by Techmind** [comment]
2 hearths probably on dazzle or maybe souls str + % heart so he can outheal all dmg if venge was not 1-2 shot.

**Comment by Techmind** [comment]
https://imgur.com/a/fH51F

0 stats, all stats from items

I have 3k hp anyway + 240 armor, the only stuff that actually matters dmg is 60 pure dmg from mkb.

My record was 300+ stacks before dying, could not screenshot fast enought.

**Comment by Techmind** [comment]
Managed to get 340 - https://imgur.com/a/1SISF (rarefication so i can faster recharge 2nd and 3rd, probably rearm could work even better.)

**Comment by leviathan13** [comment]
Use silver item on them to break passive. Alternatively, the fountain should also apply break to avoid these things altogether.

**Comment by ForbiddenFruitPOD** [comment]
After playing with it, I have come to the conclusion that Lingering Souls - Damage is OP. My reasoning is that it adds base damage, not bonus damage, so the extra damage from Lingering Souls - Damage can be further amplified by other abilities, such as God's Strength. Lingering Souls - Damage should changed to bonus damage, rather than base damage.

**Comment by darklordabc** [comment]
I tend to agree with @ForbiddenFruitPOD, base damage is a much bigger boost than bonus damage, we had this problem with the Roshanify ability increasing base damage and being mixed with abilities that multipled damge. @DrTeaSpoon maybe Lingering souls should be bonus damage instead? What ya rekon.

**Comment by darklordabc** [comment]
I think Foutain should apply break.

**Comment by DankBudd** [comment]
e53a39d
