### ISSUE TITLE
Suggestion: Turn the vote for custom skills back to 50% to approve

### ISSUE THREAD

**Issue by 1ran-wang** [darklordabc/Legends-of-Dota-Redux#1438]
It's almost impossible to get 100% approve for any vote.

**Comment by Techmind** [comment]
Upvote, we have regualr lod, if we want non-custom abilities.

**Comment by darklordabc** [comment]
Sorry we have talked about this issue a lot, and the rationale for having custom abilities being disablable by one person is to attracted new players who might be put off facing all the new abilities. I understand the counterarguments but I'm still not convinced they outweigh the benefit to new players. If you have any other suggestions on this topic I'll hear them out.

**Comment by Whitebored** [comment]
1. Griefing/trolling (Easy to just "nope" everyone else cuz u feel like it).
2. You play Lodr for it's features, if you dont look for it's features -> you dont play it.
3. People who are turned off easily will pretty much sort themselfs out of the picture anyways.
  - (Regardless of how much you baby them and turns out: wasn't worth your time).
4. This setting makes it harder to play Lodr for people who actually are intrested in the mod.
5. By common sense alone, should be around 50/50 ish.
6. Let people discover all of Lodr, it's entirerity and what it has to offer. Thats the fun part after all.
7. The decision to try something new already was made when they looked up the mod and this voting mechanism only has the opposite effect.


- Regards, Whiteboard.
