### ISSUE TITLE
Daytime based abilities

### ISSUE THREAD

**Issue by ForbiddenFruitPOD** [darklordabc/Legends-of-Dota-Redux#1457]
**Daybreak:**  Ultimate ability. Turns night into day and increases daytime sight range by 500 for your team.
Cooldown: 60/120/80 seconds
Scepter upgrade: grants unobstructed vision to yourself and each of your teammates when casted

**Heatwave:**  AOE. Enemies in the target area take magic damage per second.
Range: 700
AOE: 250
Damage per Second: int * 0.5 / int * 0.75 / int * 1.00 / int * 1.25
Duration: 4 seconds
Cooldown: 6 seconds
Mana Cost: 120
Scepter Upgrade: Has 1400 range and disables targets' regeneration/lifesteal during daytime.

**Archon Form:** Passive. Ultimate ability. During daytime increases attack range and causes a percentage of your attack damage is pure damage while granting damage reduction
Pure Damage percentage: 20/25/30
damage reduction percentage: 10/15/20
attack range bonus: 100/175/250

So, if your attack damage is 100, then when you attack, and have level 3 archon form during daytime, you would deal 70 physical damage, and 30 pure damage. The 70 physical damage would then be subject to armor.

**Far Sight:** Reveals the target area. Global range. Has truesight if casted during daytime
Area: 2000/2500/3500/4000
Duration: 15 seconds
Cooldown: 15 seconds

**Comment by Whitebored** [comment]
Daybreak: Ought to be limited to only self with unobstructed vision, to make it onpar with Darkness for balance.

Heatwave: Much needed some more anti-healing mechanics in this game mod.

Archon: A simple powerhouse ability that probably will be picked as often as fury swipes soon as people gets the wiff on it.

Far Sight: 4k AoE true sight vision with 0 downtime is suffice to say OP.

Needs to have either: 

- Longer cooldown.
- Shorter duration.
- Smaller AoE.
- Not have truesight.

Otherwise cool stuff besides Far Sight being OP af with global vision with zero downtime.

Looking forward to abusing these new abilities ingame soon as they're added.

- Whiteboard.

**Comment by ForbiddenFruitPOD** [comment]
What about:

**Far Sight:** Reveals the target area. Global range.
Area: 1500/2000/2500/3000
Duration: 8 seconds
Cooldown: 15 seconds
Scepter upgrade:  Has truesight if casted during daytime

**Comment by Whitebored** [comment]
Since it's not an ultimate, this is alot of uptime still (with octarine core in consideration).

I'd put the cooldown on Far Sight at 30 seconds and duration at 5 seconds.
 - That would make the ability an instant revealer for a moment of truth/during a clash.

Otherwise if you are looking for a more permanent observer variant of it:
60s cooldown - 15s duration.

- With the second option, it becomes less frequent and more of a location being area denied pre-fight that gets translocated every 45s (before CDR). Unless enemy team are dumbasses ofc and charges right into battle while it's up.

- Regards, Whiteboard.
