### ISSUE TITLE
Improvement of Patreon's service.

### ISSUE THREAD

**Issue by 1ran-wang** [darklordabc/Legends-of-Dota-Redux#1467]
What about let 5 dollar Patreons able to select a skill to make it unable to be banned and have an extra ban in ban phase. I think it will attract more ppl to became paterons.

because it's totally balanced as skill ban are for all players. It just increased the impact of patreons.

**Comment by darklordabc** [comment]
Are you a patreon now?

**Comment by Whitebored** [comment]
That's just awful for multiple reasons, mainly because it's litterally pay2win.

In no shape or form should money affect the game it'self by external factors.

The game is to remain intact at all times.

 - Regards, Whiteboard.

**Comment by darklordabc** [comment]
I've been thinking of ways to add perks for Patreon users, and it's probably not going to be _purely_ cosmetic, but I also want to avoid significant gameplay advantages, but very small bonuses, like this ban thing does not seem too unfair to me. I'm also thinking of having maybe mostly cosmetic bonuses for heroes that only Patreon users have, or perhaps special mutators or settings only available for Patreon users.

**Comment by Whitebored** [comment]
It does im afraid. This method is not the way to go.

Settings and custom abilities made by hand pre-game that will intregate into the game is fine (and actually adds some more flavor, which ontop of that is optional by host settings and not mandatory).

Having extra bans at your disposal vs those who doesn't pay for it is just bad and the definition of unfair.

However making abilities unbannable opens up the possability of ruining the game entirely.
 - It's such a small step on it's own, but opens up the possability nonetheless of ruining the entire game for everyone.

And why that is, is because that abilities now becomes < UNBANNABLE >because someone payed for that.

Imagine having a couple of people donating to LodR (as there appears to allready be) having about 1-3 (i'd say 2 is a good amount for that payment) safelocking about 6-10 abilities from the pool.
Now they are now there to stay forever and you can't do shit about it.

Which will ofc be the most beloved cancer and spammed abilities of all time:
- Duel
- Borrowed Time
- Essence Shift
- Etc.

And thats pretty much the only thing you're ever going to see every game ever, since people love that shit.

That will make the game boring simply because I, someone else or a couple of others payed 5 bucks and make the game repetetive, that's not what makes LodR great. It's the customisation.

And in the long run people will just get bored of it and stop playing LoDr all together because they're fed up with the same shit everygame and move on to other things.

It's bad for the game in the long run for a few donations that will ultimatively dissapear soon as people lose intrest, that this specific suggestion helps reinforce to happen much much much more sooner than it would naturally occur.

You would essentially kill your own game with this method.

Hence the intregrity is of outmost importance - that is why people are willing to pay in the first place.

- Regards, Whiteboard.

**Comment by Whitebored** [comment]
I forgot to adress the special mutator concept on this topic, sorry about that.

That as well, to have things exclusively hidden behind a pay-wall is surely gonna piss people off and rack up some bad reputation about the game.

Just to make things clear, people making donations to LoDr should on the sole reason to be to help it grow by funding the developer team (who does a great job at what they do) and not give players any ingame advantages at all or exclusive content that changes how the game is played in exchange for currency.

It is an act of good will, not a trade off on the game's greatness for money.

- Regards, Whiteboard.

**Comment by ForbiddenFruitPOD** [comment]
I think this feature is unneeded and unfair. If you want to prevent certain abilities from being banned you can already do that - by hosting a custom game where only the host has bans.

**Comment by 1ran-wang** [comment]
well i agree the point that protect a skill from baning is unfair. But I fail to see why Extra ban is also unfair. 

And here is another advice: 
set minimum patreons subscription to 1 dollar/month and let them gain a tiny bonus. (ie 500 gold at start / 2 extra free TP that unsellable /1 attribute bonus)

Or

Let patreons are able to test beta version of map, which contains new abilities and new Mutator



And I don't think pure donation gonna work, at least some visual effect is minimum requirement, For me, I payed 46 bucks to a Dota2 custom game, not only because the map was good, but also because the new skin for characters.

**Comment by Whitebored** [comment]
As to adress the additional bans topic, that's just plain unfair.

As of why that is unfair there is a simple question to be asked.

- What do you use bans for.

You use them to get rid of abilities/things you dont want to see your enemies picking/using.
This is applicable to any game out there that allows any shape or form of custimsation.

And one team having X additional bans vs the other team who simply has the flat amount provided by the game is immediatly gonna be at a disadvantage.

What happens next is that you start locking down the enemy team of what they are enable to pick and start cornering them even before the game has begun.

Bans are a crucial component of the game that very much indeed affects and changes how people play the game.

I'll go ahead and copy paste my own previous reply as to respond to Techies who keeps pushing the Pay2win concept and for wanting to sacrifice integrity of the game for currency by giving people ingame advantages/power over others who does not pay.

---
Just to make things clear, people making donations to LoDr should on the sole reason to be to help it grow by funding the developer team (who does a great job at what they do) and not give players any ingame advantages at all or exclusive content that changes how the game is played in exchange for currency.
---

If you wanna make a great game dear developers, stop listening to suggestions like these - posted by TechiesTheOne who seems to have a one-track-mind of pay2win that will secure the destruction of this game one step at the time.

If you wanna destroy the game for a few hundred bucks, I recomend we skip ahead to the part where I can buy a button ingame that destroys the enemy HQ.

On general topic of what you actually can add to the game without harming it is chat wheel commands.
Those are fun to play around with and if youre a donater you can have some fun with those spammable quotes and also show off that you're a patreon for this project.

- Regards, Whiteboard.
