### ISSUE TITLE
Suggestion: add punishment system for lod.

### ISSUE THREAD

**Issue by 1ran-wang** [darklordabc/Legends-of-Dota-Redux#1471]
For people who abandoned Should add a punishment for next game. 

Maybe 20% gold reduction or 10 sec respawn addition.

**Comment by Whitebored** [comment]
Considering that would even be possible: It would just make lodr even more broken and unfair than it allready is.

The correct way to go about this is simply enabling the abbandoning system there is already in Valves game engine.

Having a 5-15min timer before being able to join a new lobby.

Allthough that would also be a bad idea, since the people who leaves are casuals and inept at the game (which is why they left in the first place) will only achieve a huge drop in playes for this mod.

Now say for this instance this could be done, a penalty for leaving and not being able to rejoin for a while if you game was not safe to leave: You could weed out the less intrested people and in the long run have more dedicated people sticking around which would be a smaller but much higher in quality terms of a playerbase of the mod.

That is an option dev's might want to consider.

- Regards, Whiteboard.

**Comment by Wouterz90** [comment]
Yes this would turn a player that left a game away for more games if he ever comes back. I think the punishment can't really be used since a lot of players are playing with bots and that also punishes them.

**Comment by ForbiddenFruitPOD** [comment]
If there is to be any punishment system it should only apply to all_allowed or classic.
