### ISSUE TITLE
New Item Feedback: Extra Life

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#1477]
Another item is going to be added to the late game meta of redux. This is to address a specific problem. In late game redux (and sometimes earlier) what determines a hero fight is in who jumps who first, so there is a lot of hiding and a lot of highly mobile heroes waiting to pounce any hero willing to push. Even if you have 20k gold, the power of first strike is so significant that even getting maxed out items wont necessarily save you, this new item will.
![image](https://user-images.githubusercontent.com/16277198/41624340-bd6cc536-7458-11e8-842c-041406ba0f12.png)
It will cost an extremely high amount of gold so it's only going to be significant in late stage games where money is getting up to the 10k mark. It will probably cost 5k to begin with. What it does is that it prevents you from dying if an enemy jumps on you, when you would die, you get full health and mana and cooldowns refreshed. This will allow players to be able to push and withstand a surprise attack. 

Please leave any feedback on the item here.

**Comment by Whitebored** [comment]
Yea, games are supposed to end at some point.

And for the record, what determines a game is someone being caught offguard - ergo fucking up.
 - Thats what causes people to jump them in the first place.

Being able to buy Aegis on crack is just gonna make games farm and defend oriented hence prolong it more than it has to be.

This item will only favour the one who farms the most and is ahead of the enemy team, will be abused as fuck, instead of being some kind of a second-chance item youre looking for.

What usually determines hero fights in lod though is the builds people pick, but adressing a skilled playerbase, this is an all around bad idéa to implement as it will only reinforce solo-snowballing and pretty much everything else becomes obsolete meta-wise.

- Regards, Whiteboard.

**Comment by darklordabc** [comment]
How did I know you weren't going to like the idea. 

> Yea, games are supposed to end at some point.

This will help that. Like you go on to say, this will be an aegis on crack, what do people do with an Aegis? They push and take risks they dont usally take. 

>This item will only favour the one who farms the most and is ahead of the enemy team, will be abused as fuck, instead of being some kind of a second-chance item youre looking for.

The item is intended for players who already have a ton of farm, its an item you buy pretty much after you are 6 slotted already, its meant to be something useful you would actually spend the extra money on, because as of now, after you are 6 slotted and consumed all the items, there is nothing to spend your money on.

**Comment by Whitebored** [comment]
That is true.

Same goes for regular dota as well.

Thing is though that you dont need to have anything to spend money on.

- Regards, Whiteboard.

**Comment by Whitebored** [comment]
Since I doubt youre gonna bother replying past this point, I simply just wanna mention the effects and concequences of this change to the game.

It's just gonna add an additional unescessary step to the game as this item is such a "mandatory must have" tier of an item that is the ultimate end goal to achieve with your invetory -> That everyone's gonna have it.

That theres just gonna be a second layer of people respawning to go through before the game can be ended.

Not to mention the insane abuses you can pull off with this, such as an Enigma with Reinkarnation and Black hole, pulling about 9 black holes out of own ass before finally going down and disrupting the enemy team single-handledly for about 30-40 seconds straight with penetrating disables.

Or another example of a Siege mode user who defends 3 lanes single-handed and can't be stopped.

And people are gonna leave out of boredom, if they of course hasn't fallen behind in farm and get destroyed by that alone for not having that end game mandatory inventory.

Quite possibly people might get bored of the mod alltogether since it's becoming a farming simulator.

Now you know the stuff this enables and what will happen and if you simply want to do stupid things  for your own reasons without caring about the quality of the game, go ahead.

- Regards, Whiteboard.
