### ISSUE TITLE
Perk Suggestions for Grimstroke

### ISSUE THREAD

**Issue by ForbiddenFruitPOD** [darklordabc/Legends-of-Dota-Redux#1506]
1 - Spells with range 800 or greater have 25% less cooldown

2 - Spells with range 800 or greater have 15% more spell amp

3 - Soulbind binds another hero to the target.

4 - Souldbind has 2 charges.

**Comment by Whitebored** [comment]
5: Abilities that successfully applies a debuff on an enemy hero has it's cooldown reduced by 25%.
 - Does not include stuns, hexes and silences.

6: Abilities that applies a debuff has 25% shorter cooldown (The Windrunner version instead of casting).
 - Does not include stuns, hexes and silences.

7: Dealing ability damage to above 1 hero per cast, deals 10% additional damage per extra hero affected by the same cast (to that additional hero).
 - Chain lightning upwards effect, to honor his multi-target shenaniganz.

8: Dealing ability damage to an enemy hero grants vision over that unit (non-truesight) for 5 seconds.

9: Spellvamp when abilities deals damage to more than 1 unit at once.

10: Debuffing an enemy hero as Grimstroke also slows them for (if already slowed: an additional) 50%.

Sidenote: Preferably you wanna make a perk for a hero that is beyond 1 single ability, hence opening up possabilities for customisation that is LodR's greatest feature.
 - Like the 2 first suggestions on the above post.

- Regards, Whiteboard.

**Comment by arkydon** [comment]
Single Unit Targeting spells deal 20% more damage.

**Comment by Wouterz90** [comment]
> Spells with range 800 or greater have 15% more spell amp

I like this, next update will have it.
