### ISSUE TITLE
Suggestion: Double Levels for abilities

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#691]
Hallo can you add double levelling mutator : skills that can be levelled up to 8 times and 6 times and make it weaker on lower levels and a little bit stronger on upper levels. like it was in LoD official before it was removed

**Comment by darklordabc** [comment]
Unfortuntely this is not very easy to make. Abilities levels are not flexible, so you would require to make a new version of every ability, hundreds of extra abilities. The original LoD made it possible because it used a script to generate all these hundreds of abilities, but it still ended up being too difficult too maintain. Prehaps there is some other way, but as far as I can tell, its too hard to implement to be worth it.

**Comment by darklordabc** [comment]
I'm going to close this as its unlikely this will be worked on in the next few months.
