### ISSUE TITLE
Assassinate Bug - Only criting on multiple targets

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#726]
![image](https://cloud.githubusercontent.com/assets/16277198/23005361/291eab26-f450-11e6-8078-1fe4288b1986.png)

**Comment by Wouterz90** [comment]
Tested this, had a crit on one hero. Seems very unlikely that this is true.

Pass the message along since he isnt in chat.
@bigpadaa , if you experience the bug with assasinate again, please check the combat log. If it says something like ability_lua instead of the normal attack message something is wrong with the scepter detection
