### ISSUE TITLE
Add old Techies abilities

### ISSUE THREAD

**Issue by edotenseilove** [darklordabc/Legends-of-Dota-Redux#734]
Can someone add  techies old abilities to LOD i really miss them

**Comment by Darkmega18** [comment]
Agreed. Need suicide squad and old mines back. For the sake of the ol' multi-cast mines and spark wraith into hook combo. :D.

Well, that and I really want to see if suicide squad can make you not die if you have imba purification or imba shallow grave or auto-egg/auto-time lapse so I can do Blast off into Living bomb into suicide squad.

**Comment by DankBudd** [comment]
suicide and landmines can be found in the spell library. 
but you'll need to tweak the death exceptions (kill the caster if they are affected by things like shallow grave).

**Comment by Darkmega18** [comment]
YES. BUT ALSO NO. The Party will be pooped if they break auto-life saver moves. (OP mode required) :<

**Comment by DankBudd** [comment]
suicide squad has always ignored 'life saver moves' in regular dota, why shouldnt it here?
..but i guess respecting them in op only would be ok.

**Comment by Darkmega18** [comment]
cause I thought stuff like auto-egg on phoenix, auto-time lapse on weaver and auto-shallow grave which procs and saves you even after you get killed in auto-egg when playing phoenix would block even self denies. Since it's well... auto, cause it's on fatal damage or about to take fatal damage, so I thought even if it's a self destroying ability those would block it.

**Comment by darklordabc** [comment]
@Wouterz90 could you do this?
