### ISSUE TITLE
Overflow

### ISSUE THREAD

**Issue by OtsoTurpeinen** [darklordabc/Legends-of-Dota-Redux#735]
I am not sure if you are pulling from the my old overflow github version or the more updated gitlab version: "https://gitlab.com/DrTeaSpoon/Dota2Overflow/tree/master"
just making sure you get more recent one.'
(DrTeaspoon == Otso Turpeinen)

**Comment by darklordabc** [comment]
Oh did you do overflow, what a coincidence. Somebody told me about the cool abilities in overflow, so I checked it out and starting stealing them, hope you dont mind. But no, I'm pulling from the steam workshop version.

**Comment by OtsoTurpeinen** [comment]
It's cool, If you run into script bugs you can assign me to them.
Ps. the relics might make cool mutator (designed them after unreal tournamet's "heaven of relics mutator")

**Comment by darklordabc** [comment]
Btw, I wrote your credits like this:
![image](https://cloud.githubusercontent.com/assets/16277198/23123546/e3ff4c10-f7bc-11e6-80e6-f92adb4d73fd.png)

I usually have "imported from x" but since overflow is defunct right now, and I've already done that style for your ability, I figured I'd go with this, let me know if you'd rather it say from overflow.

**Comment by OtsoTurpeinen** [comment]
Ye, thats cool. :3
