### ISSUE TITLE
Create Roshan Specific Mutator

### ISSUE THREAD

**Issue by AugurM** [darklordabc/Legends-of-Dota-Redux#748]
Now that both Lane Creep and Neutral Creep can be enhanced, Roshan needs a little pick me up.
Maybe not the x4 treatment of the jungle, unless you start selling Aegis in the shop, but the ramping power up options seems nice.

**Comment by darklordabc** [comment]
Roshan does benefit from the multiplying power of neutrals. Unfortuntely how that mutator works is it gives the bonus when a creep spawns, so you have to kill Roshan for him to benefit from the extra power levels. But I agree we could add a Roshan specific mutator, I thought maybe having like a mutator that spawns BOSSES from custom games in the rosh pit, instead of Roshan, like bosses from EBF for instance, @Yahnich .

**Comment by darklordabc** [comment]
Roshan now increases power as time continues if the neutral power mutator is enabled, also he gets  damage reduction too, this is a big butf for him.  However i agree there should be a new Roshan specific mutator so I'll leave this issue open.
