### ISSUE TITLE
Latest version (just earlier): Can't use abilities

### ISSUE THREAD

**Issue by Darkmega18** [darklordabc/Legends-of-Dota-Redux#787]
So you've got everyone spawning, and it's using the normal strat screen etc before hand and thats all well and good, but I can't cast any abilities in game cause when I hit a hotkey on an ability, passive or otherwise learnt or unlearnt it gives me an error saying the ability is not learnt when it clearly is. I also can't manually click on the ability either. Same problem. :<

**Comment by darklordabc** [comment]
This sounds like the same problem we fixed, @Wouterz90?

**Comment by Darkmega18** [comment]
literally just now? or earlier but is still occuring?

**Comment by Wouterz90** [comment]
Did I fix anything?

**Comment by darklordabc** [comment]
Remeber how we had to reshuffle abilities because their index was not aligned right?

**Comment by RissaWasTaken** [comment]
Was fine for me until recent update ~2100CEST

Screenshot of build - error message "Ability Not Learned" comes up for Power Cogs (positioned at 'W', with the _free mutator_ Flesh Heap - Attack Range newly in the 'Q' slot [used to be at right end after 'R']):
![lodrnotlearned](https://cloud.githubusercontent.com/assets/25391385/23523093/8238eea2-ff53-11e6-878c-1737301e4d58.png)


The following is my loadout (the cheap and dirty paint version):
![lodrloadout](https://cloud.githubusercontent.com/assets/25391385/23523607/9fb22d52-ff55-11e6-8f77-f77de3f4f8cc.png)
:

**Comment by darklordabc** [comment]
Thanks I'll try to reproduce this soon.

**Comment by RissaWasTaken** [comment]
Follow-up; tried again with the same settings as above, but the following build - everything seems fine.

![lodrlesh](https://cloud.githubusercontent.com/assets/25391385/23523843/65e8d46c-ff56-11e6-85e2-b7056ee1fcbb.png)

**Comment by crojucuhus** [comment]
I used default Balanced Mode settings. Picked Chen and skilled Holy Persuasion at level 1. "Ability not learned" error when I try to use it.

**Comment by crojucuhus** [comment]
It should be noted that using the build switcher fixes this problem for me.

**Comment by RissaWasTaken** [comment]
It has happened twice more.  Here is one of them.
![lodrtricks](https://cloud.githubusercontent.com/assets/25391385/23535928/8adb3858-ff8f-11e6-858b-a3e6ff6de5ea.png)

**Comment by RissaWasTaken** [comment]
We thought maybe it had something to do with the Random Flesh Heap free ability, so we just tried one with no free ability. (Otherwise, the settings loadout was the same)

I took Powershot in 'F' and got the Ability Not Learned error, so I build-swapped to Shrapnel (still in 'F'), and that worked just fine.  In the same game, my partner also got Ability Not Learned for his ulti (Elder Dragon Form), and he did a build swap twice in a row to get it back and it worked after that.  I tried at that point to swap back to Powershot from Shrapnel.

The in-game build loadout put Powershot in its slot ('F') and let me lock the new build again, but did not actually replace Shrapnel in game.  Within 30 seconds, we got the Connection Timed Out disconnect error everyone was getting last week.

I'm out of guesses. :D

**Comment by crojucuhus** [comment]
@RissaWasTaken  build swapping fixes the problem. When I had Holy Persuasion in Q and it didn't work, I build swapped to change one of my other skills. That allowed Holy Persuasion to be cast. So in your case it's not that the spell Shrapnel works vs Powershot. It was the build swapping that fixed your hero.

**Comment by darklordabc** [comment]
Resolved
