### ISSUE TITLE
Drow Aura for Strength and Intelligence

### ISSUE THREAD

**Issue by Exchy** [darklordabc/Legends-of-Dota-Redux#867]
Since we have her ultimate for each attribute, it would be good to add damage aura for each attr. as well

**Comment by darklordabc** [comment]
Good Idea.

**Comment by LoDfan** [comment]
I have a better idea: 

- Str aura is for melee damage or HP increase aura
- Int aura is for spell damage aura (nearly 10% per 100 int because 30% will be too OP) or Creep damage aura (good for Chen or other summoners builds)

If there will be all these auras for range heroes, you'll need just 3 heroes with high attribute and your team will have +300 dmg

**Comment by darklordabc** [comment]
I think that idea is a winner @LoDfan
