### ISSUE TITLE
Tower Abilities that use regular abilities

### ISSUE THREAD

**Issue by darklordabc** [darklordabc/Legends-of-Dota-Redux#877]
Apothetic Shield Tower: Find all nearby creeps and heros, if heroes are in radius, cast shield on one random one, if only creeps, cast one on random creep. 
**Template 1 - Target spells at units- examples: Walrus Kick, Paralyzing Cask, Purfication, Apothetic shield** 
Variables:
*Target allies or enemies
*Minimum amount of creeps or heros nearby before triggering (e.g. don't cast unless at least 1 hero nearby)
*Prioritize hero over creeps or not
*Cast on 1 or more targets per cast (e.g. casting mist coil on 3 nearby enemies instead of 1)
*Radius of area to search for targets, tower being the center

**Template 2 - Target spells at nearby location- examples: Nether ward, Split earth, Land mines, Chronosphere** 
Variables:
*Target allies or enemies
*Minimum amount of creeps or heros nearby before triggering (e.g. don't cast unless at least 1 hero nearby)
*Prioritize hero over creeps or not, where to click the center of the ability
*Cast on 1 or more targets per cast (e.g. casting mini chronospheres on all nearby heroes)
*Radius of area to search for targets, tower being the center

**Comment by darklordabc** [comment]
@TideSofDarK updated to just two templates, target spells and target point (including aoe) spells

**Comment by Darkmega18** [comment]
here's a load of tower suggestions for you guys that shouldn't be too hard I'd hope.

Marksmanship Tower:
Combination of Attack speed and armor (since towers don't do agility) when no hero is within 250 range with 25/50/75% damage split shots to 2 enemies. Always active.
"Drow ranger taught this tower a thing or two so that it can protect her forest while she was away."

Nuclear Tower:
Last will and immolation on steroids with a mana regeneration aura! When the tower dies it triggers a massive explosion which blows away heroes and creeps like it hit you with greater bash tower but for massive damage and stuns after the fact for 4 seconds if anything survives in a 1000 radius.  600/1200/1800 damage. But while it exists it gives off an eerie green radioactive particle effect glow that makes allies nearby regenerate mana by 5/10/15 +50%/100%/150% faster. When below 33% HP it begins generating a green immolation aura that deals 75/125/200 damage a second.
"SCIENCE IN ACTION!"

Thor Tower (Mjolnir):
Shoots faster and causes mjolnir chain lightnings to happen 10/20/30% of the time. When it comes under attack and is hit more than 5 times within the last few seconds it procs a Mjolnir barrier for 5/7/9 seconds which goes on cooldown for 15 seconds.
"Eat your heart out, Zeus!"

Armor Piercing Tower:
Periodically it triggers a sniper assassinate shot that prioritizes heroes, then catapults, then ranged and melee creeps. On hit it obliterates all the target's base armor and deals 200/300/400% bonus damage slowing the target's Move speed by 25/40/55% for 3 seconds causing a shrapnel blast split shot to enemies within 300 range that deals only 50/75/100% of the towers damage to all other targets without other modifiers. 
Has long range and 20/15/10 second cooldown, but won't trigger until atleast 5 units are near the tower. Trigger's Automatically however if a hero comes in range.
"The Sniper Shell that pierces the heavens!"

Bouncing Tower:
A tower who's shots bounces between multiple enemy units after the first losing damage. (luna glaives tower but with a tower's projectile)

Emergency Repair Tower:
A tower who upon reaching below 25% HP triggers a barrier (that looks like crimson guard) which heals the tower for 10% of it's health every second over 5/6/7 seconds and reduces incoming damage by 30/50/70% for that duration. Goes on cooldown for 60/45/30 seconds afterwards.
"Energy Field, Active!"

Frenzy Tower:
Frenzy towers from Dusk. Basically when they get low, they go enrage mode and attack a lot faster and with big bright red particle shots which deal bonus damage and splash to enemies nearby for several seconds before going on cooldown. In this the cooldown can be a lot shorter though so it keeps proccing.
"THAT'S IT, I'M MAD NOW!"

Reactive Tower:
A tower who gets more armor and regens slightly the more you hit it. Gains 0.5/0.75/1 armor and 0.5/1/1,5 regen every time it gets hit for 10 seconds when attacked. But these stacks time out by themselves and don't refresh/stack.
"This tower is almost as paranoid of being killed by the trees around it as Rizrack..."

Titan Tower:
A tower that disguises it's effect as a titan aura, but when it gets destroyed it gets mad and transforms into a titan from dusk and begins to lay waste to enemies using great cleave, Granite Aura, reactive armor, titan aura, Degen aura and Demolish and the stats of a powerful warlock golem but with structure armor but treated like a creep hero ancient. The titan lasts until it is destroyed.
"THIS ISN'T EVEN MY FINAL FORM!"

Hadouken Tower:
A tower that periodically casts a stronger version of the Saytr Energy blast at the last enemy it's tracking every 10/8/6 seconds. Travels 1000/1400/1800 range, starting at 200/250/300 size and growing to double that along the way. hits for 300/400/500 damage. In Memes mode when this triggers it also plays the hadouken sound.
"KAMEHAMEHAAAA!"

Magic Hater Tower: 
(icon should be a picture of anti-mage laughing like they do on the memes... https://img.memesuper.com/d25b09588ee4d77eb0d9107d940d7457_antimage-calls-a-magic-shop-anti-mage-meme_590-576.png this one.)
A tower that scans a massive area constantly, then, when an enemy casts a spell within it it gets [TRIGGERED] and shoots that enemy with a dispeling, slowing and highly damaging bolt of energy that makes it lose a lot of mana to boot before casting a 4 second echo shell on all allied heroes in the radius. After this it goes on cooldown for 10/9/8 seconds before it goes back to being salty. Dispels softly, slows by 15/30/45%, hurts by 300/400/500 pure damage, loses 30/40/50% of max mana taking that as magic feedback damage. (so it scales, so it's always scary)
"Magina's best student"

Anti-tank Tower: Upon hitting a hero it dyes them red causing the hero to be unable to heal for a few seconds. Every consecutive hit it deals to heroes and units it dyes red take a small percentage of their maximum health every time they get hit by it until the debuff disappears. Lasts 3/4/5 seconds on no heal debuff and deals 3/4/5% MAX HP on hit.

Necro Requiem Tower:
When it kills units it takes their souls and gains +3/6/9 bonus damage. Can gain up to the maximum souls that a aghs shadow fiend can get normally. But when the tower gets attacked by a large group of creeps and atleast 1 hero and has atleast half it's max souls (or takes more than 25% of it's health within 3 seconds) it causes a Requiem to explode from it immediately doing what requiem does normally at it's current level and healing the turret by 20/30/40% of it's health.
"Shadow fiend's storage Silo for wandering souls."

Alarm Tower:
When the tower gets attacked by overwhelming forces (less than 3 allied creeps nearby, and atleast 5 enemies or a hero) it sounds an alarm that deafens enemies causing them to get greatly slowed for 1/1.5/2 seconds and disarmed for double that. During this it spawns in it's own reinforcements of timed life creeps with bonus health and attack speed for 3 seconds (which also spawn more creeps if double creeps is on) Then goes on cooldown for 20/15/10 seconds. The alarm creeps don't provide gold if possible.
"Snake? Snake?! SNAAAAAAAAAKE!"

Vengeance Tower:
Units near this tower and the tower itself gains bonus damage, and when any unit dies near the turret it has a 10/20/30% percentage chance of being brought back as a spooky full HP reflection illusion of the unit under the tower's control which attacks along with the creeps. These spooky creeps only last 6 seconds but the creeps deal 100% damage while taking 150% themselves.
"Summons the vengeful spirits of dieing units to fight for it once more."

Catacomb Tower:
Spawns weak zombies at a slower rate than a tombstone. These zombies go down in a couple of hits. But if enemies die near it the cooldown for spawning another wave of zombies goes down quicker causing a lot more zombies to appear. The zombies do their usual "eat the people on low HP and slow them a lot" thing. Each wave has 8/7/6 second cooldown where it spawns 2/3/4 zombies within it's area who attack at enemies, but goes down by 0.25/0.5/0.75 seconds each time an enemy dies near it. A hero dieing under it causes it to spawn 3/4/5 waves of zombies in quick succession. :3 
"It seems this tower was accidentally build on an ancient graveyard."
