### ISSUE TITLE
Some things to put into hero perk bonuses

### ISSUE THREAD

**Issue by Darkmega18** [darklordabc/Legends-of-Dota-Redux#898]
Centaur self damaging: Flowers from cherub.

Earth spirit: Granite Aura, Earthsunder, OP earthsunder, aftershock redux, Natural order(?), 

Techies: Recon Systems, Eldritch antimagic, Fire Trap, OP cluster rockets, Mortars, Slag armor, Fireball, Fireblast, Ignite, Unrefined Fireblast, Living Bomb, Detonation.

Omni: The Saints Grace, Tranquil Seal, Gigagraviton, Last Resort, Purification Imba (in custom abilities), Guardian angel (custom ability), Ritual of Protection, Hurl Hammer, Global Dispel, Threatening Bolt.

Zeus: Thundergods vengeance, Lightning Shield

Viper and veno: Caustic Finale, envenomed weapon.

didn't go through all of them. But yeah. theres some I saw.

edit: As a sidenote, Slag armor doesn't apply on direct hit (the burning icon above the head and DoT) but it applies just fine if you splash someone with it off a siege attack since you can make it hit the turret by hitting creeps near the turret then with aghs cause of tower armor it just burns down by like half health in one shot which is super tasty. Direct hit is probably meant to apply that sort of DoT to enemies but it doesn't. :V

**Comment by darklordabc** [comment]
These are really great, thank you for all the work you did in finding them. I think I added them all here: https://github.com/darklordabc/Legends-of-Dota-Redux/commit/37a2dba30890c517a2232eee7780d19b0b6f124a
p.s: I didnt added slag armor because its not really explosive, also ignire didnt seem explosive enough for me either. Saints Grace is already light. Also, I'm very grateful for this already, but it would be great if you could make changes to the abilities yourself, its super simple and allows me to work on other stuff.

**Comment by darklordabc** [comment]
@Darkmega18

**Comment by Darkmega18** [comment]
Roger that on slag and ignite. they were sorta "on the side" kinda things. I also thought of "nature" set for people like prophet or treant perhaps instead of charges for living armor or "teleportation" which is kinda meh. and ok, I'll give it a look. I was just worried about being unable to find localized names cause of having to look through all the other bits. so figured you'd all know where they were more easily to put them in. :)

**Comment by darklordabc** [comment]
Do you think there is enough nature ones? That is a pretty good idea.
