### ISSUE TITLE
Aftershock Troll Combos

### ISSUE THREAD

**Issue by LoDfan** [darklordabc/Legends-of-Dota-Redux#950]
The list of troll combos with Aftershock is outdated. It doesn't take into consideration talents and custom skills.
What should be added:
All skills with cd <=5 sec (including neutral and custom skills) Some of the most useful are roshan's slam and MK Mischief
Skills with cd <5 sec influenced by talents (QoP no cd dagger, Dazzle 1 sec cd Poison Touch, Luna 2 sec cd Lucent Beam  and others)
Cd reductions skills (cd reduction flash heap and other custom abilities)

I don't think any perma bash/control build is funny to play.

**Comment by darklordabc** [comment]
Okay, so heres what i did. I made original aftershock a single player ability. I've improved aftershock redux, so that it acts the same as original aftershock, BUT, if the ability used has less than 5 second cooldown, the aftershock ability will go on cooldown, this means we dont have to predefine what abilities are troll combos.

**Comment by darklordabc** [comment]
I'll close this because its sorted, but let me know what you think about my solution.

**Comment by LoDfan** [comment]
5 second cooldown before cd reduction or after? Will AS go on cd after using frostbite with octarine and 20-25% cd reduction talent?

**Comment by darklordabc** [comment]
after reductions

**Comment by LoDfan** [comment]
Great! Thank you very much for these changes!
