### ISSUE TITLE
Memory leaks abilities (causing lagging)

### ISSUE THREAD

**Issue by LODonly** [darklordabc/Legends-of-Dota-Redux#959]
I found there some not optimized abilities what cause lagging (it seems summons or objects aren't removed and remain on the map):
AW ult (may be redux version is more laggy)
Redux version of PhantomLancer ult
Pocket factory

AW ult with redux version make game unplayable at 10th min of the game

**Comment by darklordabc** [comment]
Not sure how to fix these short of removing those abilities.

**Comment by LoDfan** [comment]
Found some more issues with ML:
AW ult with any illusion creating abilities. The most laggy combination is with MK ult. Lags remains after illusions disappear! And game speed is only reducing with each illusion spawning by AW ult clone.
Phoenix model with illusion abilities or just PL ult. I guest it's because of perk. May be illusions want to cast a supernova on death? After Phoenix left the game lags stopped.
