### ISSUE TITLE
One Punch! can be self-cast

### ISSUE THREAD

**Issue by DankBudd** [darklordabc/Legends-of-Dota-Redux#976]
this is probably a bug?
it can also target teammates other than yourself, but i think that's intended because it doesn't deal damage to them.

**Comment by AugurM** [comment]
Seems like a feature to me.
I would vote for it to remain that way.

**Comment by Darkmega18** [comment]
correct Augur. it is a feature albeit a silly and slightly annoying one. because in dusk Hero can comically punch himself then use his justice leap thing to get the bonus distance from anywhere without having to punch an enemy so you can use it as a chase or a quick get away. however just by itself without the leap (which gains the bonus jump distance equal to one punch's knockback distance for a few seconds after) that feature is null so it's basically just an atomic facepalm for misclicking. ;)

**Comment by darklordabc** [comment]
Yeah, let's just leave it as is for now until it becomes an issue.
